;;; leuven-theme.el --- Awesome Emacs color theme on dark background

;; Copyright (C) 2003-2017 Free Software Foundation, Inc.

;; Author: Fabrice Niessen <(concat "fniessen" at-sign "pirilampo.org")>
;; URL: https://github.com/fniessen/emacs-leuven-theme
;; Version: 20170101.1105
;; Keywords: color theme

;; This file is part of GNU Emacs.

;; GNU Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; GNU Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This elegant Org-enhancing color theme "leuven" ROCKS!
;; ... and not just for Org mode.
;;
;; To use it, put the following in your Emacs configuration file:
;;
;;   (load-theme 'leuven t)
;;
;; Requirements: Emacs 24.
;;
;; NOTE -- Would you like implement a version of this for dark backgrounds,
;; please do so!  I'm willing to integrate it...

;;; Code:

;;; Options.

(defgroup leuven nil
  "Leuven theme options.
The theme has to be reloaded after changing anything in this group."
  :group 'faces)

(defcustom leuven-scale-outline-headlines t
  "Scale `outline' (and `org') level-1 headlines."
  :type 'boolean
  :group 'leuven)

;;; Theme Faces.

(deftheme leuven-dark
  "Face colors with a light background.
Basic, Font Lock, Isearch, Gnus, Message, Org mode, Diff, Ediff,
Flyspell, Semantic, and Ansi-Color faces are included -- and much
more...")

(let ((class '((class color) (min-colors 89)))

      ;; Leuven generic colors.
      (cancel '(:slant italic :strike-through t :foreground "#292929"))
      (clock-line '(:box (:line-width 1 :color "#436ab7") :foreground "#fffefe" :background "#161100"))
      (code-block '(:foreground "#af8b124" :background "#000000"))
      (code-inline '(:foreground "#388e2e" :background "#000000"))
      (column '(:height 1.0 :weight normal :slant normal :underline nil :strike-through nil :foreground "#2c1200" :background "#030100"))
      (completion-selected-candidate '(:weight bold :foreground "#000000" :background "#4a77d1"))
      (completion-other-candidates '(:weight bold :foreground "#fffefe" :background "#000307"))
      (completion-inline '(:weight normal :foreground "#1a1a1a" :inherit hl-line)) ; Like Google.
      (diff-added '(:background "#000300"))
      (diff-changed '(:foreground "#6845138" :background "#000919"))
      (diff-header '(:foreground "#c15138" :background "#000100"))
      (diff-hunk-header '(:foreground "#9d159c" :background "#050005"))
      (diff-none '(:foreground "#737373"))
      (diff-refine-added '(:background "#001300"))
      (diff-refine-removed '(:background "#270007"))
      (diff-removed '(:background "#080002"))
      (directory '(:weight bold :foreground "#6845138" :background "#000000"))
      (file '(:foreground "#fffefe"))
      (highlight-blue '(:background "#000508"))
      (highlight-gray '(:background "#080807"))
      (highlight-green '(:background "#000900"))
      (highlight-red '(:background "#1b0004"))
      (highlight-yellow '(:underline "#000200" :background "#000100"))
      (link '(:weight normal :underline t :foreground "#006aab"))
      (link-no-underline '(:weight normal :foreground "#006aab"))
      (mail-header-name '(:family "Sans Serif" :weight normal :foreground "#2d2d2c"))
      (mail-header-other '(:family "Sans Serif" :slant normal :foreground "#606060"))
      (mail-read '(:foreground "#292929"))
      (mail-read-high '(:foreground "#484848"))
      (mail-ticked '(:foreground "#8b0000"))
      (mail-to '(:family "Sans Serif" :underline nil :foreground "#006aab"))
      (mail-unread '(:foreground "#0b67be"))
      (mail-unread-high '(:foreground "#457eae"))
      (marked-line '(:foreground "#ad130a" :background "#300005"))
      (match '(:weight bold :background "#060900")) ; occur patterns
      (ol1 `(,@(when leuven-scale-outline-headlines (list :height 1.3)) :weight bold :overline "#2a2a2a" :foreground "#8f8f8f" :background "#030303"))
      (ol2 '(:height 1.0 :weight bold :overline "#84a1cb" :foreground "#84a1cb" :background "#000407"))
      (ol3 '(:height 1.0 :weight bold :foreground "#4c9a5a" :background "#000100"))
      (ol4 '(:height 1.0 :weight bold :slant normal :foreground "#690000"))
      (ol5 '(:height 1.0 :weight bold :slant normal :foreground "#870042"))
      (ol6 '(:height 1.0 :weight bold :slant italic :foreground "#005eae"))
      (ol7 '(:height 1.0 :weight bold :slant italic :foreground "#004e00"))
      (ol8 '(:height 1.0 :weight bold :slant italic :foreground "#4f0000"))
      (paren-matched '(:background "#001000")) ; Or take that green for region?
      (paren-unmatched '(:weight bold :underline "#850000" :foreground "#fffefe" :background "#0e0002"))
      (region '(:background "#001e3a"))
      (shadow '(:foreground "#494949"))
      (string '(:foreground "#007600")) ; or #8d0000
      (subject '(:family "Sans Serif" :weight bold :foreground "#fffefe"))
      (symlink '(:foreground "#005291"))
      (tab '(:foreground "#060606" :background "#000000"))
      (volatile-highlight '(:underline nil :foreground "#fffefe" :background "#2a1100")) ; flash-region
      (vc-branch '(:box (:line-width 1 :color "#003a00") :foreground "#fffefe" :background "#000b00"))
      (xml-attribute '(:foreground "#670000"))
      (xml-tag '(:foreground "#950082"))
      (highlight-current-tag '(:background "#00050e")) ; #010304 or #020700
  )

  (custom-theme-set-faces
   'leuven
   `(default ((,class (:foreground "#9b9b9b" :background "#000000"))))
   `(bold ((,class (:weight bold :foreground "#fffefe"))))
   `(bold-italic ((,class (:weight bold :slant italic :foreground "#fffefe"))))
   `(italic ((,class (:slant italic :foreground "#c0c0c0"))))
   `(underline ((,class (:underline t))))
   `(cursor ((,class (:background "#003668"))))

   ;; Highlighting faces.
   `(fringe ((,class (:foreground "#0a0900" :background "#000000"))))
   `(highlight ((,class ,highlight-blue)))
   `(region ((,class ,region)))
   `(secondary-selection ((,class ,match))) ; Used by Org-mode for highlighting matched entries and keywords.
   `(isearch ((,class (:weight bold :underline "#3e0000" :foreground nil :background "#200600"))))
   `(isearch-fail ((,class (:weight bold :foreground "#fffefe" :background "#3d0004"))))
   `(lazy-highlight ((,class (:underline "#3e0000" :background "#000200")))) ; isearch others
   `(trailing-whitespace ((,class (:foreground "#222222" :background "#000100"))))
   `(query-replace ((,class (:inherit isearch))))
   `(whitespace-hspace ((,class (:foreground "#101010")))) ; see also `nobreak-space'
   `(whitespace-indentation ((,class ,tab)))
   `(whitespace-line ((,class (:foreground "#9d0000" :background "#000100"))))
   `(whitespace-tab ((,class ,tab)))
   `(whitespace-trailing ((,class (:foreground "#222222" :background "#000100"))))

   ;; Mode line faces.
   `(mode-line ((,class (:box (:line-width 1 :color "#91a1d3") :foreground "#002237" :background "#436ab7"))))
   `(mode-line-inactive ((,class (:box (:line-width 1 :color "#7a7a78") :foreground "#030303" :background "#32332f"))))
   `(mode-line-buffer-id ((,class (:weight bold :foreground "#000000"))))
   `(mode-line-emphasis ((,class (:weight bold :foreground "#000000"))))
   `(mode-line-highlight ((,class (:foreground "#000200"))))

   ;; Escape and prompt faces.
   `(minibuffer-prompt ((,class (:weight bold :foreground "#fffefe" :background "#0e0a00"))))
   `(minibuffer-noticeable-prompt ((,class (:weight bold :foreground "#fffefe" :background "#0e0a00"))))
   `(escape-glyph ((,class (:foreground "#00538f"))))
   `(error ((,class (:foreground "#850000"))))
   `(warning ((,class (:weight bold :foreground "#320000"))))
   `(success ((,class (:foreground "#001800"))))

   ;; Font lock faces.
   `(font-lock-builtin-face ((,class (:foreground "#005ac6"))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "#3f3f37")))) ; #5d5d5d
   `(font-lock-comment-face ((,class (:slant italic :foreground "#3f3f37")))) ; #5d5d5d
   `(font-lock-constant-face ((,class (:foreground "#8d0000"))))
   `(font-lock-doc-face ((,class (:foreground "#2f8926"))))
   ;; `(font-lock-doc-string-face ((,class (:foreground "#007600")))) ; XEmacs only, but is used for HTML exports from org2html (and not interactively)
   `(font-lock-function-name-face ((,class (:weight normal :foreground "#2773a8"))))
   `(font-lock-keyword-face ((,class (:bold nil :foreground "#6845138")))) ; #3e59e2
   `(font-lock-preprocessor-face ((,class (:foreground "#484848"))))
   `(font-lock-regexp-grouping-backslash ((,class (:weight bold :inherit nil))))
   `(font-lock-regexp-grouping-construct ((,class (:weight bold :inherit nil))))
   `(font-lock-string-face ((,class ,string)))
   `(font-lock-type-face ((,class (:weight normal :foreground "#8855ca"))))
   `(font-lock-variable-name-face ((,class (:weight normal :foreground "#860074")))) ; #a942a8
   `(font-lock-warning-face ((,class (:weight bold :foreground "#850000"))))

   ;; Button and link faces.
   `(link ((,class ,link)))
   `(link-visited ((,class (:underline t :foreground "#590006"))))
   `(button ((,class (:underline t :foreground "#006aab"))))
   `(header-line ((,class (:weight bold :underline "#320068" :overline "#320068" :foreground "#fffefe" :background "#00050e"))))

   ;; Gnus faces.
   `(gnus-button ((,class (:weight normal))))
   `(gnus-cite-attribution-face ((,class (:foreground "#615fc2"))))
   `(gnus-cite-face-1 ((,class (:foreground "#615fc2" :background "#010101"))))
   `(gnus-cite-face-2 ((,class (:foreground "#b662b5" :background "#010101"))))
   `(gnus-cite-face-3 ((,class (:foreground "#007272" :background "#010101"))))
   `(gnus-cite-face-4 ((,class (:foreground "#b53320" :background "#010101"))))
   `(gnus-cite-face-5 ((,class (:foreground "#a680128" :background "#010101"))))
   `(gnus-cite-face-6 ((,class (:foreground "#6e2700" :background "#010101"))))
   `(gnus-cite-face-7 ((,class (:foreground "#615fc2" :background "#010101"))))
   `(gnus-cite-face-8 ((,class (:foreground "#b662b5" :background "#010101"))))
   `(gnus-cite-face-9 ((,class (:foreground "#007272" :background "#010101"))))
   `(gnus-cite-face-10 ((,class (:foreground "#b53320" :background "#010101"))))
   `(gnus-emphasis-bold ((,class (:weight bold))))
   `(gnus-emphasis-highlight-words ((,class (:foreground "#000200" :background "#fffefe"))))
   `(gnus-group-mail-1 ((,class (:weight bold :foreground "#6b0035"))))
   `(gnus-group-mail-1-empty ((,class (:foreground "#615fc2"))))
   `(gnus-group-mail-2 ((,class (:weight bold :foreground "#840014"))))
   `(gnus-group-mail-2-empty ((,class (:foreground "#b662b5"))))
   `(gnus-group-mail-3 ((,class ,mail-unread)))
   `(gnus-group-mail-3-empty ((,class ,mail-read)))
   `(gnus-group-mail-low ((,class ,cancel)))
   `(gnus-group-mail-low-empty ((,class ,cancel)))
   `(gnus-group-news-1 ((,class (:weight bold :foreground "#6b0035"))))
   `(gnus-group-news-1-empty ((,class (:foreground "#615fc2"))))
   `(gnus-group-news-2 ((,class (:weight bold :foreground "#840014"))))
   `(gnus-group-news-2-empty ((,class (:foreground "#b662b5"))))
   `(gnus-group-news-3 ((,class ,mail-unread)))
   `(gnus-group-news-3-empty ((,class ,mail-read)))
   `(gnus-group-news-4 ((,class (:weight bold :foreground "#850000"))))
   `(gnus-group-news-4-empty ((,class (:foreground "#b53320"))))
   `(gnus-group-news-5 ((,class (:weight bold :foreground "#810036"))))
   `(gnus-group-news-5-empty ((,class (:foreground "#a680128"))))
   `(gnus-group-news-6 ((,class (:weight bold :foreground "#494949"))))
   `(gnus-group-news-6-empty ((,class (:foreground "#484848"))))
   `(gnus-header-content ((,class ,mail-header-other)))
   `(gnus-header-from ((,class (:family "Sans Serif" :foreground "#fffefe"))))
   `(gnus-header-name ((,class ,mail-header-name)))
   `(gnus-header-newsgroups ((,class (:family "Sans Serif" :foreground "#004c78"))))
   `(gnus-header-subject ((,class ,subject)))
   `(gnus-picon ((,class (:foreground "#000200" :background "#000000"))))
   `(gnus-picon-xbm ((,class (:foreground "#000200" :background "#000000"))))
   `(gnus-server-closed ((,class (:slant italic :foreground "#6845138" :background "#000000"))))
   `(gnus-server-denied ((,class (:weight bold :foreground "#850000" :background "#000000"))))
   `(gnus-server-opened ((,class (:family "Sans Serif" :foreground "#000000" :foreground "#2154ba"))))
   `(gnus-signature ((,class (:slant italic :foreground "#3d3e3f"))))
   `(gnus-splash ((,class (:foreground "#460000"))))
   `(gnus-summary-cancelled ((,class ,cancel)))
   `(gnus-summary-high-ancient ((,class ,mail-unread-high)))
   `(gnus-summary-high-read ((,class ,mail-read-high)))
   `(gnus-summary-high-ticked ((,class ,mail-ticked)))
   `(gnus-summary-high-unread ((,class ,mail-unread-high)))
   `(gnus-summary-low-ancient ((,class (:slant italic :foreground "#fffefe"))))
   `(gnus-summary-low-read ((,class (:slant italic :foreground "#343434" :background "#0a0a0a"))))
   `(gnus-summary-low-ticked ((,class ,mail-ticked)))
   `(gnus-summary-low-unread ((,class (:slant italic :foreground "#fffefe"))))
   `(gnus-summary-normal-ancient ((,class (:slant italic :foreground "#0061b2"))))
   `(gnus-summary-normal-read ((,class ,mail-read)))
   `(gnus-summary-normal-ticked ((,class ,mail-ticked)))
   `(gnus-summary-normal-unread ((,class ,mail-unread)))
   `(gnus-summary-selected ((,class (:foreground "#000000" :background "#005395"))))
   `(gnus-x-face ((,class (:foreground "#fffefe" :background "#000000"))))

   ;; Message faces.
   `(message-header-name ((,class ,mail-header-name)))
   `(message-header-cc ((,class ,mail-to)))
   `(message-header-other ((,class ,mail-header-other)))
   `(message-header-subject ((,class ,subject)))
   `(message-header-to ((,class ,mail-to)))
   `(message-cited-text ((,class (:foreground "#615fc2" :background "#010101"))))
   `(message-separator ((,class (:family "Sans Serif" :weight normal :foreground "#171a1d"))))
   `(message-header-newsgroups ((,class (:family "Sans Serif" :foreground "#004c78"))))
   `(message-header-xheader ((,class ,mail-header-other)))
   `(message-mml ((,class (:foreground "#006a00"))))

   ;; Diff.
   `(diff-added ((,class ,diff-added)))
   `(diff-changed ((,class ,diff-changed)))
   `(diff-context ((,class ,diff-none)))
   `(diff-file-header ((,class ,diff-header)))
   `(diff-file1-hunk-header ((,class (:foreground "#a332a3" :background "#000405"))))
   `(diff-file2-hunk-header ((,class (:foreground "#1f7221" :background "#000405"))))
   `(diff-function ((,class (:foreground "darkgray"))))
   `(diff-header ((,class ,diff-header)))
   `(diff-hunk-header ((,class ,diff-hunk-header)))
   `(diff-index ((,class ,diff-header)))
   `(diff-indicator-added ((,class (:foreground "#005b00" :background "#000400"))))
   `(diff-indicator-changed ((,class (:background "#10319a"))))
   `(diff-indicator-removed ((,class (:foreground "#900004" :background "#0e0002"))))
   `(diff-refine-added ((,class ,diff-refine-added)))
   `(diff-refine-change ((,class (:background "#000919"))))
   `(diff-refine-removed ((,class ,diff-refine-removed)))
   `(diff-removed ((,class ,diff-removed)))

   ;; SMerge.
   `(smerge-refined-change ((,class (:background "#001e58"))))

   ;; Ediff.
   `(ediff-current-diff-A ((,class (:background "#0e0002"))))
   `(ediff-current-diff-B ((,class (:background "#000300"))))
   `(ediff-current-diff-C ((,class (:background "#001220"))))
   `(ediff-even-diff-A ((,class (:background "#101010"))))
   `(ediff-even-diff-B ((,class (:background "#101010"))))
   `(ediff-fine-diff-A ((,class (:background "#300005"))))
   `(ediff-fine-diff-B ((,class (:background "#001500"))))
   `(ediff-odd-diff-A ((,class (:background "#101010"))))
   `(ediff-odd-diff-B ((,class (:background "#101010"))))

   ;; Flyspell.
   (if (version< emacs-version "24.4")
       `(flyspell-duplicate ((,class (:underline "#007600" :inherit nil))))
     `(flyspell-duplicate ((,class (:underline (:style wave :color "#007600") :inherit nil)))))
   (if (version< emacs-version "24.4")
       `(flyspell-incorrect ((,class (:underline "#850000" :inherit nil))))
     `(flyspell-incorrect ((,class (:underline (:style wave :color "#850000") :inherit nil)))))

   ;; ;; Semantic faces.
   ;; `(semantic-decoration-on-includes ((,class (:underline ,cham-4))))
   ;; `(semantic-decoration-on-private-members-face ((,class (:background ,alum-2))))
   ;; `(semantic-decoration-on-protected-members-face ((,class (:background ,alum-2))))
   ;; `(semantic-decoration-on-unknown-includes ((,class (:background ,choc-3))))
   ;; `(semantic-decoration-on-unparsed-includes ((,class (:underline ,orange-3))))
   `(semantic-highlight-func-current-tag-face ((,class ,highlight-current-tag)))
   `(semantic-tag-boundary-face ((,class (:overline "#320068"))))
   ;; `(semantic-unmatched-syntax-face ((,class (:underline ,red-1))))

   `(Info-title-1-face ((,class ,ol1)))
   `(Info-title-2-face ((,class ,ol2)))
   `(Info-title-3-face ((,class ,ol3)))
   `(Info-title-4-face ((,class ,ol4)))
   `(ace-jump-face-foreground ((,class (:weight bold :foreground "#fffefe" :background "#320000"))))
   `(ahs-face ((,class (:background "#070902")))) ; #002141 (blue).
   `(ahs-definition-face ((,class (:background "#09000a"))))
   `(ahs-plugin-defalt-face ((,class (:background "#070902")))) ; #27000c (rose) = current.
   `(anzu-match-1 ((,class (:foreground "#fffefe" :background "#000e06"))))
   `(anzu-match-2 ((,class (:foreground "#fffefe" :background "springgreen"))))
   `(anzu-match-3 ((,class (:foreground "#fffefe" :background "#850000"))))
   `(anzu-mode-line ((,class (:foreground "#fffefe" :background "#001000"))))
   `(anzu-replace-highlight ((,class (:inherit query-replace))))
   `(anzu-replace-to ((,class (:weight bold :foreground "#6d00a9" :background "#200600"))))
   `(auto-dim-other-buffers-face ((,class (:background "#010101"))))
   `(avy-background-face ((,class (:background "#292929"))))
   `(avy-lead-face ((,class (:weight bold :foreground "#fffefe" :background "#320000"))))
   `(bbdb-company ((,class (:slant italic :foreground "#005683"))))
   `(bbdb-field-name ((,class (:weight bold :foreground "#005683"))))
   `(bbdb-field-value ((,class (:foreground "#005683"))))
   `(bbdb-name ((,class (:underline t :foreground "#620000"))))
   `(bmkp-light-fringe-autonamed ((,class (:foreground "#6d6d6d" :background "#0f0f0f"))))
   `(bmkp-light-autonamed ((,class (:background "#030303"))))
   `(bmkp-light-fringe-non-autonamed ((,class (:foreground "#000000" :background "#00121f")))) ; default
   `(bmkp-light-non-autonamed ((,class (:background "#00060a"))))
   `(browse-kill-ring-separator-face ((,class (:foreground "#850000"))))
   `(calendar-month-header ((,class (:weight bold :foreground "#837d6e" :background "#000000"))))
   `(calendar-today ((,class (:weight bold :foreground "#837d6e" :background "#000000"))))
   `(calendar-weekday-header ((,class (:weight bold :foreground "#2c6dbc"))))
   `(calendar-weekend-header ((,class (:weight bold :foreground "#7a7a7a"))))
   `(cfw:face-annotation ((,class (:foreground "#001800" :background "#850000"))))
   `(cfw:face-day-title ((,class (:foreground "#151515"))))
   `(cfw:face-default-content ((,class (:foreground "#5272ca"))))
   `(cfw:face-default-day ((,class (:weight bold))))
   `(cfw:face-disable ((,class (:foreground "#292929"))))
   `(cfw:face-grid ((,class (:foreground "#0b0b0b"))))
   `(cfw:face-header ((,class (:foreground "#2c6dbc" :background "#000000" :weight bold))))
   `(cfw:face-holiday ((,class (:foreground "#505050" :background "#00060d"))))
   `(cfw:face-periods ((,class (:foreground "#000000" :background "#004282" :slant italic))))
   `(cfw:face-saturday ((,class (:foreground "#7a7a7a" :background "#000000" :weight bold))))
   `(cfw:face-select ((,class (:foreground "#00448b" :background "#000306"))))
   `(cfw:face-sunday ((,class (:foreground "#7a7a7a" :background "#000000" :weight bold))))
   `(cfw:face-title ((,class (:height 2.0 :foreground "#5f5f5f" :weight bold :inherit variable-pitch))))
   `(cfw:face-today ((,class (:foreground "#837d6e" :background "#000000"))))
   `(cfw:face-today-title ((,class (:foreground "#000000" :background "#226bb7"))))
   `(cfw:face-toolbar ((,class (:background "#000000"))))
   `(cfw:face-toolbar-button-off ((,class (:foreground "#121212" :background "#000000"))))
   `(cfw:face-toolbar-button-on ((,class (:foreground "#686868" :background "#010101"))))
   `(change-log-date ((,class (:foreground "#7800c5"))))
   `(change-log-file ((,class (:weight bold :foreground "#00548e"))))
   `(change-log-list ((,class (:box (:line-width 1) :foreground "#00323a"))))
   `(change-log-name ((,class (:foreground "#007600"))))
   `(circe-highlight-all-nicks-face ((,class (:foreground "#6845138" :background "#030303")))) ; other nick names
   `(circe-highlight-nick-face ((,class (:foreground "#006700" :background "#030303")))) ; messages with my nick cited
   `(circe-my-message-face ((,class (:foreground "#3f3f3f" :background "#030303"))))
   `(circe-originator-face ((,class (:foreground "#6845138"))))
   `(circe-prompt-face ((,class (:foreground "#850000"))))
   `(circe-server-face ((,class (:foreground "#002032"))))
   `(comint-highlight-input ((,class (:weight bold :foreground "#6845138" :inherit nil))))
   ;; `(comint-highlight-prompt ((,class (:weight bold :foreground "#fffefe" :background "#0e0a00"))))
   `(comint-highlight-prompt ((,class (:weight bold :foreground "#6845138" :inherit nil))))

   ;; `(ac-selection-face ((,class ,completion-selected-candidate)))
   `(ac-selection-face ((,class (:weight bold :foreground "#000000" :background "#320000")))) ; TEMP For diff'ing AC from Comp.
   `(ac-candidate-face ((,class ,completion-other-candidates)))
   `(ac-completion-face ((,class ,completion-inline)))
   `(ac-candidate-mouse-face ((,class (:inherit highlight))))
   `(popup-scroll-bar-background-face ((,class (:background "#000307"))))
   `(popup-scroll-bar-foreground-face ((,class (:background "#080e13")))) ; Scrollbar (visible).

   `(company-tooltip-common-selection ((,class (:weight normal :foreground "#050400" :inherit company-tooltip-selection)))) ; Prefix + common part in tooltip (for selection).
   `(company-tooltip-selection ((,class ,completion-selected-candidate))) ; Suffix in tooltip (for selection).
   `(company-tooltip-annotation-selection ((,class (:weight normal :foreground "#050400")))) ; Annotation (for selection).

   `(company-tooltip-common ((,class (:weight normal :foreground "#920092" :inherit company-tooltip)))) ; Prefix + common part in tooltip.
   `(company-tooltip ((,class ,completion-other-candidates))) ; Suffix in tooltip.
   `(company-tooltip-annotation ((,class (:weight normal :foreground "#654312f")))) ; Annotation.

   `(company-preview-common ((,class ,completion-inline)))

   `(company-scrollbar-bg ((,class (:background "#000307"))))
   `(company-scrollbar-fg ((,class (:background "#080e13")))) ; Scrollbar (visible).

   `(compare-windows ((,class (:background "#000200"))))
   ;; `(completions-common-part ((,class (:foreground "#850000" :weight bold))))
   ;; `(completions-first-difference ((,class (:foreground "#001800" :weight bold))))
   `(compilation-error ((,class (:weight bold :foreground "#850000")))) ; Used for grep error messages.
   `(compilation-info ((,class (:weight bold :foreground "#6376d6")))) ; Used for grep hits.
   `(compilation-line-number ((,class (:weight bold :foreground "#86008f"))))
   `(compilation-warning ((,class (:weight bold :foreground "#320000"))))
   `(compilation-mode-line-exit ((,class (:weight bold :foreground "#001800")))) ; :exit[matched]
   `(compilation-mode-line-fail ((,class (:weight bold :foreground "#470049")))) ; :exit[no match]
   `(compilation-mode-line-run ((,class (:weight bold :foreground "#320000")))) ; :run
   `(css-property ((,class (:foreground "#005400"))))
   `(css-selector ((,class (:weight bold :foreground "#6845138"))))
   `(custom-button ((,class (:box (:line-width 2 :style released-button) :foreground "#fffefe" :background "lightgrey"))))
   `(custom-button-mouse ((,class (:box (:line-width 2 :style released-button) :foreground "#fffefe" :background "#070707"))))
   `(custom-button-pressed ((,class (:box (:line-width 2 :style pressed-button) :foreground "#fffefe" :background "#101010"))))
   `(custom-button-pressed-unraised ((,class (:underline t :foreground "#a332a3"))))
   `(custom-button-unraised ((,class (:underline t))))
   `(custom-changed ((,class (:foreground "#000000" :background "#6845138"))))
   `(custom-comment ((,class (:background "#0d0d0d"))))
   `(custom-comment-tag ((,class (:foreground "#ad89125"))))
   `(custom-documentation ((,class (nil))))
   `(custom-face-tag ((,class (:family "Sans Serif" :height 1.2 :weight bold))))
   `(custom-group-tag ((,class (:height 1.2 :weight bold :foreground "#6845138"))))
   `(custom-group-tag-1 ((,class (:family "Sans Serif" :height 1.2 :weight bold :foreground "#850000"))))
   `(custom-invalid ((,class (:foreground "#000200" :background "#850000"))))
   `(custom-link ((,class (:underline t :foreground "#6845138"))))
   `(custom-modified ((,class (:foreground "#000000" :background "#6845138"))))
   `(custom-rogue ((,class (:foreground "#200009" :background "#fffefe"))))
   `(custom-saved ((,class (:underline t))))
   `(custom-set ((,class (:foreground "#6845138" :background "#000000"))))
   `(custom-state ((,class (:foreground "#006d00"))))
   `(custom-themed ((,class (:foreground "#000000" :background "#6845138"))))
   `(custom-variable-button ((,class (:weight bold :underline t))))
   `(custom-variable-tag ((,class (:family "Sans Serif" :height 1.2 :weight bold :foreground "#6845138"))))
   `(custom-visibility ((,class ,link)))
   `(diff-hl-change ((,class (:foreground "#8962130" :inherit diff-changed))))
   `(diff-hl-delete ((,class (:foreground "#9d0000" :inherit diff-removed))))
   `(diff-hl-dired-change ((,class (:weight bold :foreground "#fffefe" :background "#340000"))))
   `(diff-hl-dired-delete ((,class (:weight bold :foreground "#8a0000"))))
   `(diff-hl-dired-ignored ((,class (:weight bold :foreground "#000000" :background "#1f1d13"))))
   `(diff-hl-dired-insert ((,class (:weight bold :foreground "#1e1e1f"))))
   `(diff-hl-dired-unknown ((,class (:foreground "#000000" :background "#7365ea"))))
   `(diff-hl-insert ((,class (:foreground "#006d00" :inherit diff-added))))
   `(diff-hl-unknown ((,class (:foreground "#000000" :background "#7365ea"))))
   `(diary-face ((,class (:foreground "#002344"))))
   `(dircolors-face-asm ((,class (:foreground "#fffefe"))))
   `(dircolors-face-backup ((,class (:foreground "#fffefe"))))
   `(dircolors-face-compress ((,class (:foreground "#850000"))))
   `(dircolors-face-dir ((,class ,directory)))
   `(dircolors-face-doc ((,class (:foreground "#fffefe"))))
   `(dircolors-face-dos ((,class (:foreground "#006a00"))))
   `(dircolors-face-emacs ((,class (:foreground "#fffefe"))))
   `(dircolors-face-exec ((,class (:foreground "#006a00"))))
   `(dircolors-face-html ((,class (:foreground "#fffefe"))))
   `(dircolors-face-img ((,class (:foreground "#840086"))))
   `(dircolors-face-lang ((,class (:foreground "#fffefe"))))
   `(dircolors-face-lang-interface ((,class (:foreground "#fffefe"))))
   `(dircolors-face-make ((,class (:foreground "#fffefe"))))
   `(dircolors-face-objet ((,class (:foreground "#fffefe"))))
   `(dircolors-face-package ((,class (:foreground "#fffefe"))))
   `(dircolors-face-paddb ((,class (:foreground "#fffefe"))))
   `(dircolors-face-ps ((,class (:foreground "#fffefe"))))
   `(dircolors-face-sound ((,class (:foreground "#003567"))))
   `(dircolors-face-tar ((,class (:foreground "#850000"))))
   `(dircolors-face-text ((,class (:foreground "#fffefe"))))
   `(dircolors-face-yacc ((,class (:foreground "#fffefe"))))
   `(dired-directory ((,class ,directory)))
   `(dired-header ((,class ,directory)))
   `(dired-ignored ((,class (:strike-through t :foreground "#850000"))))
   `(dired-mark ((,class ,marked-line)))
   `(dired-marked ((,class ,marked-line)))
   `(dired-symlink ((,class ,symlink)))
   `(diredp-compressed-file-suffix ((,class (:foreground "#850000"))))
   `(diredp-date-time ((,class (:foreground "#7800c5"))))
   `(diredp-dir-heading ((,class ,directory)))
   `(diredp-dir-name ((,class ,directory)))
   `(diredp-dir-priv ((,class ,directory)))
   `(diredp-exec-priv ((,class (:background "#004200"))))
   `(diredp-executable-tag ((,class (:foreground "#006a00" :background "#000000"))))
   `(diredp-file-name ((,class ,file)))
   `(diredp-file-suffix ((,class (:foreground "#1a1a1a"))))
   `(diredp-flag-mark-line ((,class ,marked-line)))
   `(diredp-ignored-file-name ((,class ,shadow)))
   `(diredp-read-priv ((,class (:background "#00469a"))))
   `(diredp-write-priv ((,class (:foreground "#000000" :background "#770000"))))
   `(elfeed-search-filter-face ((,class (:foreground "#1b1b1b"))))
   ;; `(eww-form-checkbox ((,class ())))
   ;; `(eww-form-select ((,class ())))
   ;; `(eww-form-submit ((,class ())))
   `(eww-form-text ((,class (:weight bold :foreground "#5f7890" :background "#001b31"))))
   ;; `(eww-form-textarea ((,class ())))
   `(file-name-shadow ((,class ,shadow)))
   `(font-latex-bold-face ((,class (:weight bold :foreground "#fffefe"))))
   `(fancy-narrow-blocked-face ((,class (:foreground "#34333c"))))
   `(flycheck-color-mode-line-error-face ((, class (:background "#780000"))))
   `(flycheck-color-mode-line-warning-face ((, class (:background "#320000"))))
   `(flycheck-color-mode-line-info-face ((, class (:background "#000200"))))
   `(font-latex-italic-face ((,class (:slant italic :foreground "#c0c0c0"))))
   `(font-latex-math-face ((,class (:foreground "#6845138"))))
   `(font-latex-sectioning-1-face ((,class (:family "Sans Serif" :height 2.7 :weight bold :foreground "#003d83"))))
   `(font-latex-sectioning-2-face ((,class ,ol1)))
   `(font-latex-sectioning-3-face ((,class ,ol2)))
   `(font-latex-sectioning-4-face ((,class ,ol3)))
   `(font-latex-sectioning-5-face ((,class ,ol4)))
   `(font-latex-sedate-face ((,class (:foreground "#6d0000"))))
   `(font-latex-string-face ((,class (:weight bold :foreground "#0051e2"))))
   `(font-latex-verbatim-face ((,class (:foreground "#af8b124" :background "#000000" :inherit nil))))
   `(git-commit-summary-face ((,class (:foreground "#fffefe"))))
   `(git-commit-comment-face ((,class (:slant italic :foreground "#5d5d5d"))))
   `(google-translate-text-face ((,class (:foreground "#505050" :background "#020202"))))
   `(google-translate-phonetic-face ((,class (:inherit shadow))))
   `(google-translate-translation-face ((,class (:weight normal :foreground "#0050b9" :background "#02070a"))))
   `(google-translate-suggestion-label-face ((,class (:foreground "#850000"))))
   `(google-translate-suggestion-face ((,class (:slant italic :underline t))))
   `(google-translate-listen-button-face ((,class (:height 0.8))))
   `(helm-action ((,class (:foreground "#fffefe"))))
   `(helm-bookmark-file ((,class ,file)))
   `(helm-bookmarks-su-face ((,class (:foreground "#850000"))))
   `(helm-buffer-directory ((,class ,directory)))
   `(helm-buffer-process ((,class (:foreground "#007400"))))
   `(helm-candidate-number ((,class (:foreground "#fffefe" :background "#000200"))))
   `(helm-dir-heading ((,class (:foreground "#6845138" :background "#200009"))))
   `(helm-dir-priv ((,class (:foreground "#bc442d" :background "#101010"))))
   `(helm-ff-directory ((,class ,directory)))
   `(helm-ff-dotted-directory ((,class ,directory)))
   `(helm-ff-executable ((,class (:foreground "#003900" :background "#000000"))))
   `(helm-ff-file ((,class (:foreground "#fffefe"))))
   `(helm-ff-invalid-symlink ((,class (:foreground "#000200" :background "#850000"))))
   `(helm-ff-symlink ((,class ,symlink)))
   `(helm-file-name ((,class (:foreground "#6845138"))))
   `(helm-gentoo-match-face ((,class (:foreground "#850000"))))
   `(helm-grep-lineno ((,class ,shadow)))
   `(helm-grep-match ((,class ,match)))
   `(helm-grep-running ((,class (:weight bold :foreground "#000000"))))
   `(helm-isearch-match ((,class (:background "#000600"))))
   `(helm-lisp-show-completion ((,class ,volatile-highlight))) ; See `helm-dabbrev'.
   ;; `(helm-ls-git-added-copied-face ((,class (:foreground ""))))
   ;; `(helm-ls-git-added-modified-face ((,class (:foreground ""))))
   ;; `(helm-ls-git-conflict-face ((,class (:foreground ""))))
   ;; `(helm-ls-git-deleted-and-staged-face ((,class (:foreground ""))))
   ;; `(helm-ls-git-deleted-not-staged-face ((,class (:foreground ""))))
   ;; `(helm-ls-git-modified-and-staged-face ((,class (:foreground ""))))
   `(helm-ls-git-modified-not-staged-face ((,class (:foreground "#860074"))))
   ;; `(helm-ls-git-renamed-modified-face ((,class (:foreground ""))))
   ;; `(helm-ls-git-untracked-face ((,class (:foreground ""))))
   `(helm-match ((,class ,match)))
   `(helm-moccur-buffer ((,class (:foreground "#0063c8"))))
   `(helm-selection ((,class ,highlight-blue)))
   `(helm-selection-line ((,class ,highlight-gray)))
   `(helm-separator ((,class (:foreground "#850000"))))
   `(helm-source-header ((,class ,ol1)))
   `(helm-swoop-target-line-block-face ((,class (:background "#0e1b00" :foreground "#b3b3b3"))))
   `(helm-swoop-target-line-face ((,class ,volatile-highlight)))
   `(helm-swoop-target-word-face ((,class (:weight bold :foreground nil :background "#200600"))))
   `(helm-visible-mark ((,class ,marked-line)))
   `(helm-w3m-bookmarks-face ((,class (:underline t :foreground "#001220"))))
   `(highlight-changes ((,class (:foreground nil)))) ;; blue "#966811d"
   `(highlight-changes-delete ((,class (:strike-through nil :foreground nil)))) ;; red "#a60024"
   `(highlight-symbol-face ((,class (:background "#000100"))))
   `(hl-line ((,class ,highlight-green))) ; Highlight current line.
   `(hl-tags-face ((,class ,highlight-current-tag))) ; ~ Pair highlighting (matching tags).
   `(holiday-face ((,class (:foreground "#505050" :background "#00060d"))))
   `(html-helper-bold-face ((,class (:weight bold :foreground "#fffefe"))))
   `(html-helper-italic-face ((,class (:slant italic :foreground "#fffefe"))))
   `(html-helper-underline-face ((,class (:underline t :foreground "#fffefe"))))
   `(html-tag-face ((,class (:foreground "#6845138"))))
   `(ilog-non-change-face ((,class (:height 2.0 :foreground "#8855ca"))))
   `(ilog-change-face ((,class (:height 2.0 :foreground "#007400"))))
   `(ilog-echo-face ((,class (:height 2.0 :foreground "#005ac6"))))
   `(ilog-load-face ((,class (:foreground "#860074"))))
   `(ilog-message-face ((,class (:foreground "#484848"))))
   `(indent-guide-face ((,class (:foreground "#101010"))))
   `(info-file ((,class (:family "Sans Serif" :height 1.8 :weight bold :box (:line-width 1 :color "#8a63130") :foreground "#003d83" :background "#000d1c"))))
   `(info-header-node ((,class (:underline t :foreground "#320000")))) ; nodes in header
   `(info-header-xref ((,class (:underline t :foreground "#0048a5")))) ; cross references in header
   `(info-index-match ((,class (:weight bold :foreground nil :background "#200600")))) ; when using `i'
   `(info-menu-header ((,class ,ol2))) ; menu titles (headers) -- major topics
   `(info-menu-star ((,class (:foreground "#fffefe")))) ; every 3rd menu item
   `(info-node ((,class (:underline t :foreground "#6845138")))) ; node names
   `(info-quoted-name ((,class ,code-inline)))
   `(info-string ((,class ,string)))
   `(info-title-1 ((,class ,ol1)))
   `(info-xref ((,class (:underline t :foreground "#006aab")))) ; unvisited cross-references
   `(info-xref-visited ((,class (:underline t :foreground "#a332a3")))) ; previously visited cross-references
   ;; js2-highlight-vars-face (~ auto-highlight-symbol)
   `(js2-function-param ((,class (:foreground "#0a0c00"))))
   `(js2-error ((,class (:box (:line-width 1 :color "#7b0000") :background "#0c0002")))) ; DONE.
   `(js2-external-variable ((,class (:foreground "#850000")))) ; DONE.
   `(js2-function-param ((,class (:foreground "#006537"))))
   `(js2-instance-member ((,class (:foreground "#7f00b0"))))
   `(js2-jsdoc-html-tag-delimiter ((,class (:foreground "#001800"))))
   `(js2-jsdoc-html-tag-name ((,class (:foreground "#000200"))))
   `(js2-jsdoc-tag ((,class (:foreground "#3f4e5c"))))
   `(js2-jsdoc-type ((,class (:foreground "#005683"))))
   `(js2-jsdoc-value ((,class (:foreground "#2b1a0a"))))
   `(js2-magic-paren ((,class (:underline t))))
   `(js2-private-function-call ((,class (:foreground "#321b00"))))
   `(js2-private-member ((,class (:foreground "#2b1a0a"))))
   `(js2-warning ((,class (:underline "#320000"))))

   ;; Org non-standard faces.
   `(leuven-org-deadline-overdue ((,class (:foreground "#850011"))))
   `(leuven-org-deadline-today ((,class (:weight bold :foreground "#837d6e" :background "#000000"))))
   `(leuven-org-deadline-tomorrow ((,class (:foreground "#005100"))))
   `(leuven-org-deadline-future ((,class (:foreground "#005100"))))
   `(leuven-gnus-unseen ((,class (:weight bold :foreground "#5a0000"))))
   `(leuven-gnus-date ((,class (:foreground "#4d0026"))))
   `(leuven-gnus-size ((,class (:foreground "#003000"))))

   `(light-symbol-face ((,class (:background "#000100"))))
   `(linum ((,class (:foreground "#333333" :background "#040404"))))
   `(log-view-file ((,class (:foreground "#8a63130" :background "#000405"))))
   `(log-view-message ((,class (:foreground "#0e1b00"))))
   `(lui-button-face ((,class ,link)))
   `(lui-highlight-face ((,class (:box '(:line-width 1 :color "#9d0000") :foreground "#9d0000" :background "#000100")))) ; my nickname
   `(lui-time-stamp-face ((,class (:foreground "#7800c5"))))
   `(magit-blame-header ((,class (:inherit magit-diff-file-header))))
   `(magit-blame-heading ((,class (:overline "#2a2a2a" :foreground "#850000" :background "#070707"))))
   `(magit-blame-hash ((,class (:overline "#2a2a2a" :foreground "#850000" :background "#070707"))))
   `(magit-blame-name ((,class (:overline "#2a2a2a" :foreground "#2f8926" :background "#070707"))))
   `(magit-blame-date ((,class (:overline "#2a2a2a" :foreground "#6845138" :background "#070707"))))
   `(magit-blame-summary ((,class (:overline "#2a2a2a" :weight bold :foreground "#575757" :background "#070707"))))
   `(magit-branch ((,class ,vc-branch)))
   `(magit-diff-add ((,class ,diff-added)))
   `(magit-diff-del ((,class ,diff-removed)))
   `(magit-diff-file-header ((,class (:height 1.1 :weight bold :foreground "#00548e"))))
   `(magit-diff-hunk-header ((,class ,diff-hunk-header)))
   `(magit-diff-none ((,class ,diff-none)))
   `(magit-header ((,class (:foreground "#000000" :background "#770000"))))
   `(magit-item-highlight ((,class (:background "#000405"))))
   `(magit-item-mark ((,class ,marked-line)))
   `(magit-log-head-label ((,class (:box (:line-width 1 :color "#6845138" :style nil)))))
   `(magit-log-tag-label ((,class (:box (:line-width 1 :color "#003a00" :style nil)))))
   `(magit-section-title ((,class (:family "Sans Serif" :height 1.8 :weight bold :foreground "#003d83" :inherit nil))))
   `(makefile-space-face ((,class (:background "#5d002c"))))
   `(makefile-targets ((,class (:weight bold :foreground "#6845138"))))
   ;; `(markdown-blockquote-face ((,class ())))
   `(markdown-bold-face ((,class (:inherit bold))))
   ;; `(markdown-comment-face ((,class ())))
   ;; `(markdown-footnote-face ((,class ())))
   ;; `(markdown-header-delimiter-face ((,class ())))
   ;; `(markdown-header-face ((,class ())))
   `(markdown-header-face-1 ((,class ,ol1)))
   `(markdown-header-face-2 ((,class ,ol2)))
   `(markdown-header-face-3 ((,class ,ol3)))
   `(markdown-header-face-4 ((,class ,ol4)))
   `(markdown-header-face-5 ((,class ,ol5)))
   `(markdown-header-face-6 ((,class ,ol6)))
   ;; `(markdown-header-rule-face ((,class ())))
   `(markdown-inline-code-face ((,class ,code-inline)))
   `(markdown-italic-face ((,class (:inherit italic))))
   ;; `(markdown-language-keyword-face ((,class ())))
   ;; `(markdown-line-break-face ((,class ())))
   `(markdown-link-face ((,class ,link-no-underline)))
   ;; `(markdown-link-title-face ((,class ())))
   ;; `(markdown-list-face ((,class ())))
   ;; `(markdown-math-face ((,class ())))
   ;; `(markdown-metadata-key-face ((,class ())))
   ;; `(markdown-metadata-value-face ((,class ())))
   ;; `(markdown-missing-link-face ((,class ())))
   ;; `(markdown-pre-face ((,class ())))
   ;; `(markdown-reference-face ((,class ())))
   ;; `(markdown-strike-through-face ((,class ())))
   `(markdown-url-face ((,class ,link)))
   `(match ((,class ,match)))           ; Used for grep matches.
   `(mc/cursor-bar-face ((,class (:height 1.0 :foreground "#000000" :background "#1b65c6"))))
   `(mc/cursor-face ((,class (:inverse-video t))))
   `(mc/region-face ((,class (:inherit region))))
   `(mm-uu-extract ((,class ,code-block)))
   `(moccur-current-line-face ((,class (:foreground "#fffefe" :background "#000000"))))
   `(moccur-face ((,class (:foreground "#fffefe" :background "#000100"))))
   `(next-error ((,class ,volatile-highlight)))
   `(nobreak-space ((,class (:background "#000b12"))))
   `(nxml-attribute-local-name-face ((,class ,xml-attribute)))
   `(nxml-attribute-value-delimiter-face ((,class (:foreground "#006d00"))))
   `(nxml-attribute-value-face ((,class (:foreground "#006d00"))))
   `(nxml-comment-content-face ((,class (:slant italic :foreground "#850000"))))
   `(nxml-comment-delimiter-face ((,class (:foreground "#850000"))))
   `(nxml-element-local-name ((,class ,xml-tag)))
   `(nxml-element-local-name-face ((,class (:foreground "#6845138"))))
   `(nxml-processing-instruction-target-face ((,class (:foreground "#6b00cb"))))
   `(nxml-tag-delimiter-face ((,class (:foreground "#6845138"))))
   `(nxml-tag-slash-face ((,class (:foreground "#6845138"))))
   `(org-agenda-block-count ((,class (:weight bold :foreground "#2b2b2c"))))
   `(org-agenda-calendar-event ((,class (:weight bold :foreground "#0059ab" :background "#00060d"))))
   `(org-agenda-calendar-sexp ((,class (:foreground "#0058a4" :background "#000203"))))
   `(org-agenda-clocking ((,class (:foreground "#fffefe" :background "#161100"))))
   `(org-agenda-column-dateline ((,class ,column)))
   `(org-agenda-current-time ((,class (:underline t :foreground "#2c6dbc"))))
   `(org-agenda-date ((,class (:height 1.6 :weight bold :foreground "#2c6dbc"))))
   `(org-agenda-date-today ((,class (:height 1.6 :weight bold :foreground "#837d6e" :background "#000000"))))
   `(org-agenda-date-weekend ((,class (:height 1.6 :weight bold :foreground "#7a7a7a"))))
   `(org-agenda-diary ((,class (:weight bold :foreground "#006d00" :background "#001720"))))
   `(org-agenda-dimmed-todo-face ((,class (:foreground "#161100"))))
   `(org-agenda-done ((,class (:foreground "#727272"))))
   `(org-agenda-filter-category ((,class (:weight bold :foreground "#320000"))))
   `(org-agenda-filter-tags ((,class (:weight bold :foreground "#320000"))))
   `(org-agenda-restriction-lock ((,class (:background "#550000"))))
   `(org-agenda-structure ((,class (:height 1.6 :weight bold :foreground "#005291"))))
   `(org-archived ((,class (:foreground "#222222"))))
   `(org-beamer-tag ((,class (:box (:line-width 1 :color "#210a00") :foreground "#a4a4a4" :background "#000100"))))
   `(org-block ((,class ,code-block)))
   `(org-block-background ((,class (:background "#000000")))) ;; :inherit fixed-pitch))))
   `(org-block-begin-line ((,class (:underline "#2b2a2d" :foreground "#727272" :background "#0a0a04"))))
   `(org-block-end-line ((,class (:overline "#2b2a2d" :foreground "#727272" :background "#0a0a04"))))
   `(org-checkbox ((,class (:weight bold :box (:line-width 1 :style pressed-button) :foreground "#868686" :background "#2d2d2d"))))
   `(org-clock-overlay ((,class (:foreground "#000000" :background "#3e647e"))))
   `(org-code ((,class ,code-inline)))
   `(org-column ((,class ,column)))
   `(org-column-title ((,class ,column)))
   `(org-date ((,class (:underline t :foreground "#607ce3"))))
   `(org-default ((,class (:foreground "#9b9b9b" :background "#000000"))))
   `(org-dim ((,class (:foreground "#282828"))))
   `(org-document-info ((,class (:foreground "#818181"))))
   `(org-document-info-keyword ((,class (:foreground "#00538f" :background "#00040d"))))
   `(org-document-title ((,class (:family "Sans Serif" :height 1.8 :weight bold :foreground "#fffefe"))))
   `(org-done ((,class (:weight bold :box (:line-width 1 :color "#1d1d1d") :foreground "#1d1d1d" :background "#030303"))))
   `(org-drawer ((,class (:foreground "#00213e"))))
   `(org-ellipsis ((,class (:underline nil :box (:line-width 1 :color "#343434") :foreground "#343434" :background "#000200")))) ; #010600
   `(org-example ((,class (:foreground "#6845138" :background "#000200"))))
   `(org-footnote ((,class (:underline t :foreground "#00538f"))))
   `(org-formula ((,class (:foreground "#500000"))))
   `(org-headline-done ((,class (:height 1.0 :weight normal :strike-through t :foreground "#262626"))))
   `(org-hide ((,class (:foreground "#090909"))))
   `(org-inlinetask ((,class (:box (:line-width 1 :color "#050505") :foreground "#505050" :background "#000000"))))
   `(org-latex-and-related ((,class (:foreground "#3a6ca0" :background "#000000"))))
   `(org-level-1 ((,class ,ol1)))
   `(org-level-2 ((,class ,ol2)))
   `(org-level-3 ((,class ,ol3)))
   `(org-level-4 ((,class ,ol4)))
   `(org-level-5 ((,class ,ol5)))
   `(org-level-6 ((,class ,ol6)))
   `(org-level-7 ((,class ,ol7)))
   `(org-level-8 ((,class ,ol8)))
   `(org-link ((,class ,link)))
   `(org-list-dt ((,class (:weight bold :foreground "#436ab7"))))
   `(org-macro ((,class (:weight bold :foreground "#231100"))))
   `(org-meta-line ((,class (:slant normal :foreground "#00538f" :background "#00040d"))))
   `(org-mode-line-clock ((,class (:box (:line-width 1 :color "#436ab7") :foreground "#fffefe" :background "#340000"))))
   `(org-mode-line-clock-overrun ((,class (:weight bold :box (:line-width 1 :color "#436ab7") :foreground "#000000" :background "#770000"))))
   `(org-number-of-items ((,class (:weight bold :foreground "#000000" :background "#00360a"))))
   `(org-property-value ((,class (:foreground "#005c00"))))
   `(org-quote ((,class (:slant italic :foreground "#5d5d5d" :background "#000000"))))
   `(org-scheduled ((,class (:foreground "#9b9b9b"))))
   `(org-scheduled-previously ((,class (:foreground "#0d64c4"))))
   `(org-scheduled-today ((,class (:weight bold :foreground "#837d6e" :background "#000000"))))
   `(org-sexp-date ((,class (:foreground "#0059ab"))))
   `(org-special-keyword ((,class (:weight bold :foreground "#004700" :background "#000200"))))
   `(org-table ((,class (:foreground "#388e2e" :background "#000200")))) ;; :inherit fixed-pitch))))
   `(org-tag ((,class (:weight normal :slant italic :foreground "#2e3135" :background "#000000"))))
   `(org-target ((,class (:foreground "#5b0027"))))
   `(org-time-grid ((,class (:foreground "#121212"))))
   `(org-todo ((,class (:weight bold :box (:line-width 1 :color "#2f1113") :foreground "#2f1113" :background "#090001"))))
   `(org-upcoming-deadline ((,class (:foreground "#6c0000"))))
   `(org-verbatim ((,class (:foreground "#0063c8" :background "#000001"))))
   `(org-verse ((,class (:slant italic :foreground "#5d5d5d" :background "#040404"))))
   `(org-warning ((,class (:weight bold :foreground "#fffefe" :background "#000b17"))))
   `(outline-1 ((,class ,ol1)))
   `(outline-2 ((,class ,ol2)))
   `(outline-3 ((,class ,ol3)))
   `(outline-4 ((,class ,ol4)))
   `(outline-5 ((,class ,ol5)))
   `(outline-6 ((,class ,ol6)))
   `(outline-7 ((,class ,ol7)))
   `(outline-8 ((,class ,ol8)))
   `(pabbrev-debug-display-label-face ((,class (:background "#001200"))))
   `(pabbrev-suggestions-face ((,class (:weight bold :foreground "#000000" :background "#850000"))))
   `(pabbrev-suggestions-label-face ((,class (:weight bold :foreground "#000000" :background "#7800c5"))))
   `(paren-face-match ((,class ,paren-matched)))
   `(paren-face-mismatch ((,class ,paren-unmatched)))
   `(paren-face-no-match ((,class ,paren-unmatched)))
   `(persp-selected-face ((,class (:weight bold :foreground "#000306"))))
   `(powerline-active1 ((,class (:foreground "#002237" :background "#949494" :inherit mode-line))))
   `(powerline-active2 ((,class (:foreground "#002237" :background "#285ea0" :inherit mode-line))))
   `(powerline-inactive1 ((,class (:foreground "#030303" :background "#5e5e5e" :inherit mode-line-inactive))))
   `(powerline-inactive2 ((,class (:foreground "#030303" :background "#292929" :inherit mode-line-inactive))))
   `(rainbow-delimiters-depth-1-face ((,class (:foreground "#535464"))))
   `(rainbow-delimiters-depth-2-face ((,class (:foreground "#1d3f7f"))))
   `(rainbow-delimiters-depth-3-face ((,class (:foreground "#3b3c31"))))
   `(rainbow-delimiters-depth-4-face ((,class (:foreground "#29492a"))))
   `(rainbow-delimiters-depth-5-face ((,class (:foreground "#5c4343"))))
   `(rainbow-delimiters-depth-6-face ((,class (:foreground "#374f8c"))))
   `(rainbow-delimiters-depth-7-face ((,class (:foreground "#454541"))))
   `(rainbow-delimiters-depth-8-face ((,class (:foreground "#1e3c1f"))))
   `(rainbow-delimiters-depth-9-face ((,class (:foreground "#5e4849"))))
   `(rainbow-delimiters-mismatched-face ((,class ,paren-unmatched)))
   `(rainbow-delimiters-unmatched-face ((,class ,paren-unmatched)))
   `(recover-this-file ((,class (:weight bold :background "#780000"))))
   `(rng-error ((,class (:weight bold :foreground "#850000" :background "#0a0003"))))
   `(sh-heredoc ((,class (:foreground "#6845138" :background "#000306"))))
   `(sh-quoted-exec ((,class (:foreground "#800031"))))
   `(shadow ((,class ,shadow)))         ; Used for grep context lines.
   `(shell-option-face ((,class (:foreground "#006a00"))))
   `(shell-output-2-face ((,class (:foreground "#6845138"))))
   `(shell-output-3-face ((,class (:foreground "#7800c5"))))
   `(shell-output-face ((,class (:foreground "#fffefe"))))
   ;; `(shell-prompt-face ((,class (:weight bold :foreground "#000200"))))
   `(shm-current-face ((,class (:background "#070600"))))
   `(shm-quarantine-face ((,class (:background "lemonchiffon"))))
   `(show-paren-match ((,class ,paren-matched)))
   `(show-paren-mismatch ((,class ,paren-unmatched)))
   `(sml-modeline-end-face ((,class (:background "#003369")))) ; #436ab7
   `(sml-modeline-vis-face ((,class (:background "#005da8"))))

   ;; `(sp-pair-overlay-face                        
   ;; `(sp-show-pair-enclosing                      
   ;; `(sp-show-pair-match-face                      ; ~ Pair highlighting (matching tags).
   ;; `(sp-show-pair-mismatch-face                  
   ;; `(sp-wrap-overlay-closing-pair                
   ;; `(sp-wrap-overlay-face                        
   ;; `(sp-wrap-overlay-opening-pair                
   ;; `(sp-wrap-tag-overlay-face                    

   `(speedbar-button-face ((,class (:foreground "#006d00"))))
   `(speedbar-directory-face ((,class (:foreground "#ad89125"))))
   `(speedbar-file-face ((,class (:foreground "#006264"))))
   `(speedbar-highlight-face ((,class ,volatile-highlight)))
   `(speedbar-selected-face ((,class (:underline t :foreground "#850000"))))
   `(speedbar-tag-face ((,class (:foreground "#a32829"))))
   `(svn-status-directory-face ((,class ,directory)))
   `(svn-status-filename-face ((,class (:weight bold :foreground "#00548e"))))
   `(svn-status-locked-face ((,class (:weight bold :foreground "#850000"))))
   `(svn-status-marked-face ((,class ,marked-line)))
   `(svn-status-marked-popup-face ((,class (:weight bold :foreground "#003900"))))
   `(svn-status-switched-face ((,class (:slant italic :foreground "#3e3e3e"))))
   `(svn-status-symlink-face ((,class ,symlink)))
   `(svn-status-update-available-face ((,class (:foreground "#320000"))))
   `(tex-verbatim ((,class (:foreground "#6845138"))))
   `(tool-bar ((,class (:box (:line-width 1 :style released-button) :foreground "#fffefe" :background "#1b1b1b"))))
   `(tooltip ((,class (:foreground "#fffefe" :background "#000000"))))
   `(trailing-whitespace ((,class (:background "#050009"))))
   `(traverse-match-face ((,class (:weight bold :foreground "#790dcf"))))
   `(vc-annotate-face-3F3FFF ((,class (:foreground "#4844106" :background "#fffefe"))))
   `(vc-annotate-face-3F6CFF ((,class (:foreground "#4844106" :background "#fffefe"))))
   `(vc-annotate-face-3F99FF ((,class (:foreground "#004193" :background "#fffefe"))))
   `(vc-annotate-face-3FC6FF ((,class (:foreground "#004193" :background "#fffefe"))))
   `(vc-annotate-face-3FF3FF ((,class (:foreground "#001729" :background "#fffefe"))))
   `(vc-annotate-face-3FFF56 ((,class (:foreground "#001600" :background "#fffefe"))))
   `(vc-annotate-face-3FFF83 ((,class (:foreground "#001400" :background "#fffefe"))))
   `(vc-annotate-face-3FFFB0 ((,class (:foreground "#001400" :background "#fffefe"))))
   `(vc-annotate-face-3FFFDD ((,class (:foreground "#001729" :background "#fffefe"))))
   `(vc-annotate-face-56FF3F ((,class (:foreground "#001600" :background "#fffefe"))))
   `(vc-annotate-face-83FF3F ((,class (:foreground "#000c00" :background "#fffefe"))))
   `(vc-annotate-face-B0FF3F ((,class (:foreground "#000c00" :background "#fffefe"))))
   `(vc-annotate-face-DDFF3F ((,class (:foreground "#000500" :background "#fffefe"))))
   `(vc-annotate-face-F6FFCC ((,class (:foreground "#fffefe" :background "#000100"))))
   `(vc-annotate-face-FF3F3F ((,class (:foreground "#780000" :background "#fffefe"))))
   `(vc-annotate-face-FF6C3F ((,class (:foreground "#780000" :background "#fffefe"))))
   `(vc-annotate-face-FF993F ((,class (:foreground "#3c0000" :background "#fffefe"))))
   `(vc-annotate-face-FFC63F ((,class (:foreground "#3c0000" :background "#fffefe"))))
   `(vc-annotate-face-FFF33F ((,class (:foreground "#000500" :background "#fffefe"))))
   `(vhl/default-face ((,class ,volatile-highlight))) ; `volatile-highlights.el'.
   `(w3m-anchor ((,class ,link)))
   `(w3m-arrived-anchor ((,class (:foreground "#6b00cb"))))
   `(w3m-bitmap-image-face ((,class (:foreground "#e0e0df" :background "#001800"))))
   `(w3m-bold ((,class (:weight bold :foreground "#fffefe"))))
   `(w3m-current-anchor ((,class (:weight bold :underline t :foreground "#6845138"))))
   `(w3m-form ((,class (:underline t :foreground "#330000"))))
   `(w3m-form-button-face ((,class (:weight bold :underline t :foreground "#e0e0df" :background "#101010"))))
   `(w3m-form-button-mouse-face ((,class (:underline t :foreground "#101010" :background "#1f7221"))))
   `(w3m-form-button-pressed-face ((,class (:weight bold :underline t :foreground "#e0e0df" :background "#101010"))))
   `(w3m-header-line-location-content-face ((,class (:foreground "#494949":background "#010101"))))
   `(w3m-header-line-location-title-face ((,class (:foreground "#4b6bcd" :background "#010101"))))
   `(w3m-history-current-url-face ((,class (:foreground "#000100"))))
   `(w3m-image-face ((,class (:weight bold :foreground "#001000"))))
   `(w3m-link-numbering ((,class (:foreground "#00192e")))) ; mouseless browsing
   `(w3m-strike-through-face ((,class (:strike-through t))))
   `(w3m-underline-face ((,class (:underline t))))

   ;; `(web-mode-block-attr-name-face ((,class ())))
   ;; `(web-mode-block-attr-value-face ((,class ())))
   ;; `(web-mode-block-comment-face ((,class ())))
   ;; `(web-mode-block-control-face ((,class ())))
   ;; `(web-mode-block-delimiter-face ((,class ())))
   ;; `(web-mode-block-face ((,class ())))
   ;; `(web-mode-block-string-face ((,class ())))
   ;; `(web-mode-bold-face ((,class ())))
   ;; `(web-mode-builtin-face ((,class ())))
   ;; `(web-mode-comment-face ((,class ())))
   ;; `(web-mode-comment-keyword-face ((,class ())))
   ;; `(web-mode-constant-face ((,class ())))
   ;; `(web-mode-css-at-rule-face ((,class ())))
   ;; `(web-mode-css-color-face ((,class ())))
   ;; `(web-mode-css-comment-face ((,class ())))
   ;; `(web-mode-css-function-face ((,class ())))
   ;; `(web-mode-css-priority-face ((,class ())))
   ;; `(web-mode-css-property-name-face ((,class ())))
   ;; `(web-mode-css-pseudo-class-face ((,class ())))
   ;; `(web-mode-css-selector-face ((,class ())))
   ;; `(web-mode-css-string-face ((,class ())))
   ;; `(web-mode-css-variable-face ((,class ())))
   ;; `(web-mode-current-column-highlight-face ((,class ())))
   `(web-mode-current-element-highlight-face ((,class (:background "#320068")))) ; #020500
   ;; `(web-mode-doctype-face ((,class ())))
   ;; `(web-mode-error-face ((,class ())))
   ;; `(web-mode-filter-face ((,class ())))
   ;; `(web-mode-folded-face ((,class ())))
   ;; `(web-mode-function-call-face ((,class ())))
   ;; `(web-mode-function-name-face ((,class ())))
   ;; `(web-mode-html-attr-custom-face ((,class ())))
   ;; `(web-mode-html-attr-engine-face ((,class ())))
   ;; `(web-mode-html-attr-equal-face ((,class ())))
   `(web-mode-html-attr-name-face ((,class ,xml-attribute)))
   ;; `(web-mode-html-attr-value-face ((,class ())))
   ;; `(web-mode-html-entity-face ((,class ())))
   `(web-mode-html-tag-bracket-face ((,class ,xml-tag)))
   ;; `(web-mode-html-tag-custom-face ((,class ())))
   `(web-mode-html-tag-face ((,class ,xml-tag)))
   ;; `(web-mode-html-tag-namespaced-face ((,class ())))
   ;; `(web-mode-inlay-face ((,class ())))
   ;; `(web-mode-italic-face ((,class ())))
   ;; `(web-mode-javascript-comment-face ((,class ())))
   ;; `(web-mode-javascript-string-face ((,class ())))
   ;; `(web-mode-json-comment-face ((,class ())))
   ;; `(web-mode-json-context-face ((,class ())))
   ;; `(web-mode-json-key-face ((,class ())))
   ;; `(web-mode-json-string-face ((,class ())))
   ;; `(web-mode-jsx-depth-1-face ((,class ())))
   ;; `(web-mode-jsx-depth-2-face ((,class ())))
   ;; `(web-mode-jsx-depth-3-face ((,class ())))
   ;; `(web-mode-jsx-depth-4-face ((,class ())))
   ;; `(web-mode-keyword-face ((,class ())))
   ;; `(web-mode-param-name-face ((,class ())))
   ;; `(web-mode-part-comment-face ((,class ())))
   `(web-mode-part-face ((,class (:background "#000000"))))
   ;; `(web-mode-part-string-face ((,class ())))
   ;; `(web-mode-preprocessor-face ((,class ())))
   `(web-mode-script-face ((,class (:background "#030304"))))
   ;; `(web-mode-sql-keyword-face ((,class ())))
   ;; `(web-mode-string-face ((,class ())))
   ;; `(web-mode-style-face ((,class ())))
   ;; `(web-mode-symbol-face ((,class ())))
   ;; `(web-mode-type-face ((,class ())))
   ;; `(web-mode-underline-face ((,class ())))
   ;; `(web-mode-variable-name-face ((,class ())))
   ;; `(web-mode-warning-face ((,class ())))
   ;; `(web-mode-whitespace-face ((,class ())))

   `(which-func ((,class (:weight bold :foreground "#000000"))))
   ;; `(which-key-command-description-face)
   ;; `(which-key-group-description-face)
   ;; `(which-key-highlighted-command-face)
   ;; `(which-key-key-face)
   `(which-key-local-map-description-face ((,class (:weight bold :background "#000203" :inherit which-key-command-description-face))))
   ;; `(which-key-note-face)
   ;; `(which-key-separator-face)
   ;; `(which-key-special-key-face)
   `(widget-button ((,class ,link)))
   `(widget-button-pressed ((,class (:foreground "#850000"))))
   `(widget-documentation ((,class (:foreground "#006d00"))))
   `(widget-field ((,class (:background "#0d0d0d"))))
   `(widget-inactive ((,class (:foreground "#5d5d5d"))))
   `(widget-single-line-field ((,class (:background "#0d0d0d"))))
   `(woman-bold ((,class (:weight bold :foreground "#7e0000"))))
   `(woman-italic ((,class (:weight bold :slant italic :foreground "#004000"))))
   `(woman-symbol ((,class (:weight bold :foreground "#7800c5"))))
   `(yas-field-debug-face ((,class (:background "#850000"))))
   `(yas-field-highlight-face ((,class (:box (:line-width 1 :color "#464646") :foreground "#fffefe" :background "#0a0e0c"))))
   ))

(custom-theme-set-variables 'leuven

  ;; highlight-sexp-mode.
  '(hl-sexp-background-color "#060404")

  '(ansi-color-faces-vector
    [default default default italic underline success warning error])

  ;; Colors used in Shell mode.
  '(ansi-color-names-vector
    ["#fffefe" "#9d0000" "#006a00" "#0e1b00" "#6845138" "#840086" "#003567" "#494949"])
 )

;;;######autoload
(when (and (boundp 'custom-theme-load-path)
           load-file-name)
  ;; Add theme folder to `custom-theme-load-path' when installing over MELPA.
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

;;;######autoload
(when (string-match "/etc/themes/$"
                    (file-name-directory (or load-file-name (buffer-file-name))))
  (message "To stay up-to-date, you should better install and use leuven-theme from MELPA.")
  (sit-for 2))

(provide-theme 'leuven-dark)

;; This is for the sake of Emacs.
;; Local Variables:
;; no-byte-compile: t
;; time-stamp-end: "$"
;; time-stamp-format: "%:y%02m%02d.%02H%02M"
;; time-stamp-start: "Version: "
;; End:

;;; leuven-theme.el ends here
