;;; leuven-theme.el --- Awesome Emacs color theme on white background

;; Copyright (C) 2003-2016 Free Software Foundation, Inc.

;; Author: Fabrice Niessen <(concat "fniessen" at-sign "pirilampo.org")>
;; URL: https://github.com/fniessen/emacs-leuven-theme
;; Version: 20161027.2101
;; Keywords: color theme

;; This file is part of GNU Emacs.

;; GNU Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; GNU Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This elegant Org-enhancing color theme "leuven" ROCKS!
;; ... and not just for Org mode.
;;
;; To use it, put the following in your Emacs configuration file:
;;
;;   (load-theme 'leuven t)
;;
;; Requirements: Emacs 24.
;;
;; NOTE -- Would you like implement a version of this for dark backgrounds,
;; please do so!  I'm willing to integrate it...

;;; Code:

;;; Options.

(defgroup leuven nil
  "Leuven theme options.
The theme has to be reloaded after changing anything in this group."
  :group 'faces)

(defcustom leuven-scale-outline-headlines t
  "Scale `outline' (and `org') level-1 headlines."
  :type 'boolean
  :group 'leuven)

;;; Theme Faces.

(deftheme leuven-dark
  "Face colors with a light background.
Basic, Font Lock, Isearch, Gnus, Message, Org mode, Diff, Ediff,
Flyspell, Semantic, and Ansi-Color faces are included -- and much
more...")

(let ((class '((class color) (min-colors 89)))

      ;; Leuven generic colors.
      (cancel '(:slant italic :strike-through t :foreground "#565656"))
      (clock-line '(:box (:line-width 1 :color "#315ba4") :foreground "#ffffff" :background "#3c3200"))
      (code-block '(:foreground "#0000f5" :background "#020201"))
      (code-inline '(:foreground "#00b700" :background "#000000"))
      (column '(:height 1.0 :weight normal :slant normal :underline nil :strike-through nil :foreground "#4c391a" :background "#0b0a09"))
      (completion-selected-candidate '(:weight bold :foreground "#000000" :background "#005cb8"))
      (completion-other-candidates '(:weight bold :foreground "#ffffff" :background "#0b0b0c"))
      (completion-inline '(:weight normal :foreground "#3f3f3f" :inherit hl-line)) ; Like Google.
      (diff-added '(:background "#070907"))
      (diff-changed '(:foreground "#0000ed" :background "#1a1a1f"))
      (diff-header '(:foreground "#e40000" :background "#050503"))
      (diff-hunk-header '(:foreground "#d400d4" :background "#0c0b0c"))
      (diff-none '(:foreground "#ababab"))
      (diff-refine-added '(:background "#172617"))
      (diff-refine-removed '(:background "#392829"))
      (diff-removed '(:background "#121010"))
      (directory '(:weight bold :foreground "#0000ed" :background "#030302"))
      (file '(:foreground "#ffffff"))
      (highlight-blue '(:background "#0e0f10"))
      (highlight-gray '(:background "#1b1b1a"))
      (highlight-green '(:background "#131612"))
      (highlight-red '(:background "#2b2121"))
      (highlight-yellow '(:underline "#101001" :background "#050604"))
      (link '(:weight normal :underline t :foreground "#0066a4"))
      (link-no-underline '(:weight normal :foreground "#0066a4"))
      (mail-header-name '(:family "Sans Serif" :weight normal :foreground "#5c5c5b"))
      (mail-header-other '(:family "Sans Serif" :slant normal :foreground "#999999"))
      (mail-read '(:foreground "#565656"))
      (mail-read-high '(:foreground "#7f7f7f"))
      (mail-ticked '(:foreground "#b21b10"))
      (mail-to '(:family "Sans Serif" :underline nil :foreground "#0066a4"))
      (mail-unread '(:foreground "#005aa7"))
      (mail-unread-high '(:foreground "#1976b1"))
      (marked-line '(:foreground "#db0000" :background "#432c2c"))
      (match '(:weight bold :background "#211d09")) ; occur patterns
      (ol1 `(,@(when leuven-scale-outline-headlines (list :height 1.3)) :weight bold :overline "#585858" :foreground "#c3c3c3" :background "#0f0f0f"))
      (ol2 '(:height 1.0 :weight bold :overline "#2b81cf" :foreground "#2b81cf" :background "#0b0c0d"))
      (ol3 '(:height 1.0 :weight bold :foreground "#00bf4c" :background "#030403"))
      (ol4 '(:height 1.0 :weight bold :slant normal :foreground "#863800"))
      (ol5 '(:height 1.0 :weight bold :slant normal :foreground "#aa1b69"))
      (ol6 '(:height 1.0 :weight bold :slant italic :foreground "#005a9b"))
      (ol7 '(:height 1.0 :weight bold :slant italic :foreground "#1e741d"))
      (ol8 '(:height 1.0 :weight bold :slant italic :foreground "#6d3703"))
      (paren-matched '(:background "#1b211b")) ; Or take that green for region?
      (paren-unmatched '(:weight bold :underline "#c90000" :foreground "#ffffff" :background "#1b1717"))
      (region '(:background "#1e2d37"))
      (shadow '(:foreground "#808080"))
      (string '(:foreground "#00a200")) ; or #a82c24
      (subject '(:family "Sans Serif" :weight bold :foreground "#ffffff"))
      (symlink '(:foreground "#125683"))
      (tab '(:foreground "#171717" :background "#000000"))
      (volatile-highlight '(:underline nil :foreground "#ffffff" :background "#48371f")) ; flash-region
      (vc-branch '(:box (:line-width 1 :color "#00681a") :foreground "#ffffff" :background "#0f170f"))
      (xml-attribute '(:foreground "#80341b"))
      (xml-tag '(:foreground "#bc1da6"))
      (highlight-current-tag '(:background "#131315")) ; #0b0b0c or #1d1a04
  )

  (custom-theme-set-faces
   'leuven-dark
   `(default ((,class (:font "DejaVu Sans" :foreground "#cccccc" :background "#000000"))))
   `(bold ((,class (:weight bold :foreground "#ffffff"))))
   `(bold-italic ((,class (:weight bold :slant italic :foreground "#ffffff"))))
   `(italic ((,class (:slant italic :foreground "#e5e5e5"))))
   `(underline ((,class (:underline t))))
   `(cursor ((,class (:background "#0c455e"))))

   ;; Highlighting faces.
   `(fringe ((,class (:foreground "#262007" :background "#000000"))))
   `(highlight ((,class ,highlight-blue)))
   `(region ((,class ,region)))
   `(secondary-selection ((,class ,match))) ; Used by Org-mode for highlighting matched entries and keywords.
   `(isearch ((,class (:weight bold :underline "#593411" :foreground nil :background "#3e2e0c"))))
   `(isearch-fail ((,class (:weight bold :foreground "#ffffff" :background "#503030"))))
   `(lazy-highlight ((,class (:underline "#593411" :background "#111100")))) ; isearch others
   `(trailing-whitespace ((,class (:foreground "#4c4c4c" :background "#050503"))))
   `(query-replace ((,class (:inherit isearch))))
   `(whitespace-hspace ((,class (:foreground "#2d2d2d")))) ; see also `nobreak-space'
   `(whitespace-indentation ((,class ,tab)))
   `(whitespace-line ((,class (:foreground "#d40000" :background "#080804"))))
   `(whitespace-tab ((,class ,tab)))
   `(whitespace-trailing ((,class (:foreground "#4c4c4c" :background "#050503"))))

   ;; Mode line faces.
   `(mode-line ((,class (:box (:line-width 1 :color "#4074d1") :foreground "#23363e" :background "#315ba4"))))
   `(mode-line-inactive ((,class (:box (:line-width 1 :color "#b1b1ac") :foreground "#0f0f0e" :background "#62635f"))))
   `(mode-line-buffer-id ((,class (:weight bold :foreground "#000000"))))
   `(mode-line-emphasis ((,class (:weight bold :foreground "#000000"))))
   `(mode-line-highlight ((,class (:foreground "#111100"))))

   ;; Escape and prompt faces.
   `(minibuffer-prompt ((,class (:weight bold :foreground "#ffffff" :background "#2e2600"))))
   `(minibuffer-noticeable-prompt ((,class (:weight bold :foreground "#ffffff" :background "#2e2600"))))
   `(escape-glyph ((,class (:foreground "#005d8a"))))
   `(error ((,class (:foreground "#c90000"))))
   `(warning ((,class (:weight bold :foreground "#523500"))))
   `(success ((,class (:foreground "#004700"))))

   ;; Font lock faces.
   `(font-lock-builtin-face ((,class (:foreground "#004e9f"))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "#72726a")))) ; #969696
   `(font-lock-comment-face ((,class (:slant italic :foreground "#72726a")))) ; #969696
   `(font-lock-constant-face ((,class (:foreground "#a82c24"))))
   `(font-lock-doc-face ((,class (:foreground "#05b10b"))))
   ;; `(font-lock-doc-string-face ((,class (:foreground "#00a200")))) ; XEmacs only, but is used for HTML exports from org2html (and not interactively)
   `(font-lock-function-name-face ((,class (:weight normal :foreground "#0071aa"))))
   `(font-lock-keyword-face ((,class (:bold nil :foreground "#0000ed")))) ; #283fa7
   `(font-lock-preprocessor-face ((,class (:foreground "#7f7f7f"))))
   `(font-lock-regexp-grouping-backslash ((,class (:weight bold :inherit nil))))
   `(font-lock-regexp-grouping-construct ((,class (:weight bold :inherit nil))))
   `(font-lock-string-face ((,class ,string)))
   `(font-lock-type-face ((,class (:weight normal :foreground "#713bb9"))))
   `(font-lock-variable-name-face ((,class (:weight normal :foreground "#a52f92")))) ; #db00db
   `(font-lock-warning-face ((,class (:weight bold :foreground "#c90000"))))

   ;; Button and link faces.
   `(link ((,class ,link)))
   `(link-visited ((,class (:underline t :foreground "#703a35"))))
   `(button ((,class (:underline t :foreground "#0066a4"))))
   `(header-line ((,class (:weight bold :underline "#47345f" :overline "#47345f" :foreground "#ffffff" :background "#131315"))))

   ;; Gnus faces.
   `(gnus-button ((,class (:weight normal))))
   `(gnus-cite-attribution-face ((,class (:foreground "#4c4ca8"))))
   `(gnus-cite-face-1 ((,class (:foreground "#4c4ca8" :background "#090909"))))
   `(gnus-cite-face-2 ((,class (:foreground "#e200e2" :background "#090909"))))
   `(gnus-cite-face-3 ((,class (:foreground "#00a0a0" :background "#090909"))))
   `(gnus-cite-face-4 ((,class (:foreground "#de0000" :background "#090909"))))
   `(gnus-cite-face-5 ((,class (:foreground "#0000f4" :background "#090909"))))
   `(gnus-cite-face-6 ((,class (:foreground "#8e4d00" :background "#090909"))))
   `(gnus-cite-face-7 ((,class (:foreground "#4c4ca8" :background "#090909"))))
   `(gnus-cite-face-8 ((,class (:foreground "#e200e2" :background "#090909"))))
   `(gnus-cite-face-9 ((,class (:foreground "#00a0a0" :background "#090909"))))
   `(gnus-cite-face-10 ((,class (:foreground "#de0000" :background "#090909"))))
   `(gnus-emphasis-bold ((,class (:weight bold))))
   `(gnus-emphasis-highlight-words ((,class (:foreground "#111100" :background "#ffffff"))))
   `(gnus-group-mail-1 ((,class (:weight bold :foreground "#83295a"))))
   `(gnus-group-mail-1-empty ((,class (:foreground "#4c4ca8"))))
   `(gnus-group-mail-2 ((,class (:weight bold :foreground "#c2004d"))))
   `(gnus-group-mail-2-empty ((,class (:foreground "#e200e2"))))
   `(gnus-group-mail-3 ((,class ,mail-unread)))
   `(gnus-group-mail-3-empty ((,class ,mail-read)))
   `(gnus-group-mail-low ((,class ,cancel)))
   `(gnus-group-mail-low-empty ((,class ,cancel)))
   `(gnus-group-news-1 ((,class (:weight bold :foreground "#83295a"))))
   `(gnus-group-news-1-empty ((,class (:foreground "#4c4ca8"))))
   `(gnus-group-news-2 ((,class (:weight bold :foreground "#c2004d"))))
   `(gnus-group-news-2-empty ((,class (:foreground "#e200e2"))))
   `(gnus-group-news-3 ((,class ,mail-unread)))
   `(gnus-group-news-3-empty ((,class ,mail-read)))
   `(gnus-group-news-4 ((,class (:weight bold :foreground "#c90000"))))
   `(gnus-group-news-4-empty ((,class (:foreground "#de0000"))))
   `(gnus-group-news-5 ((,class (:weight bold :foreground "#be0071"))))
   `(gnus-group-news-5-empty ((,class (:foreground "#0000f4"))))
   `(gnus-group-news-6 ((,class (:weight bold :foreground "#808080"))))
   `(gnus-group-news-6-empty ((,class (:foreground "#7f7f7f"))))
   `(gnus-header-content ((,class ,mail-header-other)))
   `(gnus-header-from ((,class (:family "Sans Serif" :foreground "#ffffff"))))
   `(gnus-header-name ((,class ,mail-header-name)))
   `(gnus-header-newsgroups ((,class (:family "Sans Serif" :foreground "#1d5977"))))
   `(gnus-header-subject ((,class ,subject)))
   `(gnus-picon ((,class (:foreground "#111100" :background "#000000"))))
   `(gnus-picon-xbm ((,class (:foreground "#111100" :background "#000000"))))
   `(gnus-server-closed ((,class (:slant italic :foreground "#0000ed" :background "#000000"))))
   `(gnus-server-denied ((,class (:weight bold :foreground "#c90000" :background "#000000"))))
   `(gnus-server-opened ((,class (:family "Sans Serif" :foreground "#000000" :foreground "#304994"))))
   `(gnus-signature ((,class (:slant italic :foreground "#6f7172"))))
   `(gnus-splash ((,class (:foreground "#643600"))))
   `(gnus-summary-cancelled ((,class ,cancel)))
   `(gnus-summary-high-ancient ((,class ,mail-unread-high)))
   `(gnus-summary-high-read ((,class ,mail-read-high)))
   `(gnus-summary-high-ticked ((,class ,mail-ticked)))
   `(gnus-summary-high-unread ((,class ,mail-unread-high)))
   `(gnus-summary-low-ancient ((,class (:slant italic :foreground "#ffffff"))))
   `(gnus-summary-low-read ((,class (:slant italic :foreground "#666666" :background "#1f1f1f"))))
   `(gnus-summary-low-ticked ((,class ,mail-ticked)))
   `(gnus-summary-low-unread ((,class (:slant italic :foreground "#ffffff"))))
   `(gnus-summary-normal-ancient ((,class (:slant italic :foreground "#005b9f"))))
   `(gnus-summary-normal-read ((,class ,mail-read)))
   `(gnus-summary-normal-ticked ((,class ,mail-ticked)))
   `(gnus-summary-normal-unread ((,class ,mail-unread)))
   `(gnus-summary-selected ((,class (:foreground "#000000" :background "#005a8b"))))
   `(gnus-x-face ((,class (:foreground "#ffffff" :background "#000000"))))

   ;; Message faces.
   `(message-header-name ((,class ,mail-header-name)))
   `(message-header-cc ((,class ,mail-to)))
   `(message-header-other ((,class ,mail-header-other)))
   `(message-header-subject ((,class ,subject)))
   `(message-header-to ((,class ,mail-to)))
   `(message-cited-text ((,class (:foreground "#4c4ca8" :background "#090909"))))
   `(message-separator ((,class (:family "Sans Serif" :weight normal :foreground "#3a3b3d"))))
   `(message-header-newsgroups ((,class (:family "Sans Serif" :foreground "#1d5977"))))
   `(message-header-xheader ((,class ,mail-header-other)))
   `(message-mml ((,class (:foreground "#239123"))))

   ;; Diff.
   `(diff-added ((,class ,diff-added)))
   `(diff-changed ((,class ,diff-changed)))
   `(diff-context ((,class ,diff-none)))
   `(diff-file-header ((,class ,diff-header)))
   `(diff-file1-hunk-header ((,class (:foreground "#d800d8" :background "#0d0d0e"))))
   `(diff-file2-hunk-header ((,class (:foreground "#339832" :background "#0d0d0e"))))
   `(diff-function ((,class (:foreground "darkgray"))))
   `(diff-header ((,class ,diff-header)))
   `(diff-hunk-header ((,class ,diff-hunk-header)))
   `(diff-index ((,class ,diff-header)))
   `(diff-indicator-added ((,class (:foreground "#308030" :background "#080a08"))))
   `(diff-indicator-changed ((,class (:background "#3b3b76"))))
   `(diff-indicator-removed ((,class (:foreground "#ab2a2a" :background "#1a1616"))))
   `(diff-refine-added ((,class ,diff-refine-added)))
   `(diff-refine-change ((,class (:background "#1a1a1f"))))
   `(diff-refine-removed ((,class ,diff-refine-removed)))
   `(diff-removed ((,class ,diff-removed)))

   ;; SMerge.
   `(smerge-refined-change ((,class (:background "#34344f"))))

   ;; Ediff.
   `(ediff-current-diff-A ((,class (:background "#1a1616"))))
   `(ediff-current-diff-B ((,class (:background "#070907"))))
   `(ediff-current-diff-C ((,class (:background "#003535"))))
   `(ediff-even-diff-A ((,class (:background "#2c2c2c"))))
   `(ediff-even-diff-B ((,class (:background "#2c2c2c"))))
   `(ediff-fine-diff-A ((,class (:background "#432c2c"))))
   `(ediff-fine-diff-B ((,class (:background "#0f2f0f"))))
   `(ediff-odd-diff-A ((,class (:background "#2c2c2c"))))
   `(ediff-odd-diff-B ((,class (:background "#2c2c2c"))))

   ;; Flyspell.
   (if (version< emacs-version "24.4")
       `(flyspell-duplicate ((,class (:underline "#00a200" :inherit nil))))
     `(flyspell-duplicate ((,class (:underline (:style wave :color "#00a200") :inherit nil)))))
   (if (version< emacs-version "24.4")
       `(flyspell-incorrect ((,class (:underline "#c90000" :inherit nil))))
     `(flyspell-incorrect ((,class (:underline (:style wave :color "#c90000") :inherit nil)))))

   ;; ;; Semantic faces.
   ;; `(semantic-decoration-on-includes ((,class (:underline ,cham-4))))
   ;; `(semantic-decoration-on-private-members-face ((,class (:background ,alum-2))))
   ;; `(semantic-decoration-on-protected-members-face ((,class (:background ,alum-2))))
   ;; `(semantic-decoration-on-unknown-includes ((,class (:background ,choc-3))))
   ;; `(semantic-decoration-on-unparsed-includes ((,class (:underline ,orange-3))))
   `(semantic-highlight-func-current-tag-face ((,class ,highlight-current-tag)))
   `(semantic-tag-boundary-face ((,class (:overline "#47345f"))))
   ;; `(semantic-unmatched-syntax-face ((,class (:underline ,red-1))))

   `(Info-title-1-face ((,class ,ol1)))
   `(Info-title-2-face ((,class ,ol2)))
   `(Info-title-3-face ((,class ,ol3)))
   `(Info-title-4-face ((,class ,ol4)))
   `(ace-jump-face-foreground ((,class (:weight bold :foreground "#ffffff" :background "#523500"))))
   `(ahs-face ((,class (:background "#191a18")))) ; #1f303c (blue).
   `(ahs-definition-face ((,class (:background "#131013"))))
   `(ahs-plugin-defalt-face ((,class (:background "#191a18")))) ; #38272b (rose) = current.
   `(anzu-match-1 ((,class (:foreground "#ffffff" :background "#0e1d18"))))
   `(anzu-match-2 ((,class (:foreground "#ffffff" :background "springgreen"))))
   `(anzu-match-3 ((,class (:foreground "#ffffff" :background "#c90000"))))
   `(anzu-mode-line ((,class (:foreground "#ffffff" :background "#112311"))))
   `(anzu-replace-highlight ((,class (:inherit query-replace))))
   `(anzu-replace-to ((,class (:weight bold :foreground "#7720a0" :background "#3e2e0c"))))
   `(auto-dim-other-buffers-face ((,class (:background "#080808"))))
   `(avy-background-face ((,class (:background "#565656"))))
   `(avy-lead-face ((,class (:weight bold :foreground "#ffffff" :background "#523500"))))
   `(bbdb-company ((,class (:slant italic :foreground "#346086"))))
   `(bbdb-field-name ((,class (:weight bold :foreground "#346086"))))
   `(bbdb-field-value ((,class (:foreground "#346086"))))
   `(bbdb-name ((,class (:underline t :foreground "#7c3118"))))
   `(bmkp-light-fringe-autonamed ((,class (:foreground "#a5a5a5" :background "#2b2b2b"))))
   `(bmkp-light-autonamed ((,class (:background "#0f0f0f"))))
   `(bmkp-light-fringe-non-autonamed ((,class (:foreground "#030302" :background "#003534")))) ; default
   `(bmkp-light-non-autonamed ((,class (:background "#090d0c"))))
   `(browse-kill-ring-separator-face ((,class (:foreground "#c90000"))))
   `(calendar-month-header ((,class (:weight bold :foreground "#b4a88a" :background "#030302"))))
   `(calendar-today ((,class (:weight bold :foreground "#b4a88a" :background "#030302"))))
   `(calendar-weekday-header ((,class (:weight bold :foreground "#145da7"))))
   `(calendar-weekend-header ((,class (:weight bold :foreground "#b1b1b1"))))
   `(cfw:face-annotation ((,class (:foreground "#004700" :background "#c90000"))))
   `(cfw:face-day-title ((,class (:foreground "#363636"))))
   `(cfw:face-default-content ((,class (:foreground "#2c58af"))))
   `(cfw:face-default-day ((,class (:weight bold))))
   `(cfw:face-disable ((,class (:foreground "#565656"))))
   `(cfw:face-grid ((,class (:foreground "#222222"))))
   `(cfw:face-header ((,class (:foreground "#145da7" :background "#000000" :weight bold))))
   `(cfw:face-holiday ((,class (:foreground "#888888" :background "#111214"))))
   `(cfw:face-periods ((,class (:foreground "#000000" :background "#364b75" :slant italic))))
   `(cfw:face-saturday ((,class (:foreground "#b1b1b1" :background "#000000" :weight bold))))
   `(cfw:face-select ((,class (:foreground "#244873" :background "#0d0d0e"))))
   `(cfw:face-sunday ((,class (:foreground "#b1b1b1" :background "#000000" :weight bold))))
   `(cfw:face-title ((,class (:height 2.0 :foreground "#989898" :weight bold :inherit variable-pitch))))
   `(cfw:face-today ((,class (:foreground "#b4a88a" :background "#030302"))))
   `(cfw:face-today-title ((,class (:foreground "#000000" :background "#155ea4"))))
   `(cfw:face-toolbar ((,class (:background "#000000"))))
   `(cfw:face-toolbar-button-off ((,class (:foreground "#303030" :background "#000000"))))
   `(cfw:face-toolbar-button-on ((,class (:foreground "#a1a1a1" :background "#090909"))))
   `(change-log-date ((,class (:foreground "#7818b5"))))
   `(change-log-file ((,class (:weight bold :foreground "#2c5885"))))
   `(change-log-list ((,class (:box (:line-width 1) :foreground "#005d5d"))))
   `(change-log-name ((,class (:foreground "#00a200"))))
   `(circe-highlight-all-nicks-face ((,class (:foreground "#0000ed" :background "#0f0f0f")))) ; other nick names
   `(circe-highlight-nick-face ((,class (:foreground "#009500" :background "#0f0f0f")))) ; messages with my nick cited
   `(circe-my-message-face ((,class (:foreground "#747474" :background "#0f0f0f"))))
   `(circe-originator-face ((,class (:foreground "#0000ed"))))
   `(circe-prompt-face ((,class (:foreground "#c90000"))))
   `(circe-server-face ((,class (:foreground "#28353d"))))
   `(comint-highlight-input ((,class (:weight bold :foreground "#0000ed" :inherit nil))))
   ;; `(comint-highlight-prompt ((,class (:weight bold :foreground "#ffffff" :background "#2e2600"))))
   `(comint-highlight-prompt ((,class (:weight bold :foreground "#0000ed" :inherit nil))))

   ;; `(ac-selection-face ((,class ,completion-selected-candidate)))
   `(ac-selection-face ((,class (:weight bold :foreground "#000000" :background "#523500")))) ; TEMP For diff'ing AC from Comp.
   `(ac-candidate-face ((,class ,completion-other-candidates)))
   `(ac-completion-face ((,class ,completion-inline)))
   `(ac-candidate-mouse-face ((,class (:inherit highlight))))
   `(popup-scroll-bar-background-face ((,class (:background "#0b0b0c"))))
   `(popup-scroll-bar-foreground-face ((,class (:background "#222426")))) ; Scrollbar (visible).

   `(company-tooltip-common-selection ((,class (:weight normal :foreground "#12110e" :inherit company-tooltip-selection)))) ; Prefix + common part in tooltip (for selection).
   `(company-tooltip-selection ((,class ,completion-selected-candidate))) ; Suffix in tooltip (for selection).
   `(company-tooltip-annotation-selection ((,class (:weight normal :foreground "#12110e")))) ; Annotation (for selection).

   `(company-tooltip-common ((,class (:weight normal :foreground "#cd00cd" :inherit company-tooltip)))) ; Prefix + common part in tooltip.
   `(company-tooltip ((,class ,completion-other-candidates))) ; Suffix in tooltip.
   `(company-tooltip-annotation ((,class (:weight normal :foreground "#1e11d6")))) ; Annotation.

   `(company-preview-common ((,class ,completion-inline)))

   `(company-scrollbar-bg ((,class (:background "#0b0b0c"))))
   `(company-scrollbar-fg ((,class (:background "#222426")))) ; Scrollbar (visible).

   `(compare-windows ((,class (:background "#111100"))))
   ;; `(completions-common-part ((,class (:foreground "#c90000" :weight bold))))
   ;; `(completions-first-difference ((,class (:foreground "#004700" :weight bold))))
   `(compilation-error ((,class (:weight bold :foreground "#c90000")))) ; Used for grep error messages.
   `(compilation-info ((,class (:weight bold :foreground "#3053b7")))) ; Used for grep hits.
   `(compilation-line-number ((,class (:weight bold :foreground "#a133aa"))))
   `(compilation-warning ((,class (:weight bold :foreground "#523500"))))
   `(compilation-mode-line-exit ((,class (:weight bold :foreground "#004700")))) ; :exit[matched]
   `(compilation-mode-line-fail ((,class (:weight bold :foreground "#5e335e")))) ; :exit[no match]
   `(compilation-mode-line-run ((,class (:weight bold :foreground "#523500")))) ; :run
   `(css-property ((,class (:foreground "#008400"))))
   `(css-selector ((,class (:weight bold :foreground "#0000ed"))))
   `(custom-button ((,class (:box (:line-width 2 :style released-button) :foreground "#ffffff" :background "lightgrey"))))
   `(custom-button-mouse ((,class (:box (:line-width 2 :style released-button) :foreground "#ffffff" :background "#1a1a1a"))))
   `(custom-button-pressed ((,class (:box (:line-width 2 :style pressed-button) :foreground "#ffffff" :background "#2c2c2c"))))
   `(custom-button-pressed-unraised ((,class (:underline t :foreground "#d800d8"))))
   `(custom-button-unraised ((,class (:underline t))))
   `(custom-changed ((,class (:foreground "#000000" :background "#0000ed"))))
   `(custom-comment ((,class (:background "#262626"))))
   `(custom-comment-tag ((,class (:foreground "#0000f5"))))
   `(custom-documentation ((,class (nil))))
   `(custom-face-tag ((,class (:family "Sans Serif" :height 1.2 :weight bold))))
   `(custom-group-tag ((,class (:height 1.2 :weight bold :foreground "#0000ed"))))
   `(custom-group-tag-1 ((,class (:family "Sans Serif" :height 1.2 :weight bold :foreground "#c90000"))))
   `(custom-invalid ((,class (:foreground "#111100" :background "#c90000"))))
   `(custom-link ((,class (:underline t :foreground "#0000ed"))))
   `(custom-modified ((,class (:foreground "#000000" :background "#0000ed"))))
   `(custom-rogue ((,class (:foreground "#302426" :background "#ffffff"))))
   `(custom-saved ((,class (:underline t))))
   `(custom-set ((,class (:foreground "#0000ed" :background "#000000"))))
   `(custom-state ((,class (:foreground "#009a00"))))
   `(custom-themed ((,class (:foreground "#000000" :background "#0000ed"))))
   `(custom-variable-button ((,class (:weight bold :underline t))))
   `(custom-variable-tag ((,class (:family "Sans Serif" :height 1.2 :weight bold :foreground "#0000ed"))))
   `(custom-visibility ((,class ,link)))
   `(diff-hl-change ((,class (:foreground "#0000f0" :inherit diff-changed))))
   `(diff-hl-delete ((,class (:foreground "#d30000" :inherit diff-removed))))
   `(diff-hl-dired-change ((,class (:weight bold :foreground "#ffffff" :background "#503310"))))
   `(diff-hl-dired-delete ((,class (:weight bold :foreground "#a72c10"))))
   `(diff-hl-dired-ignored ((,class (:weight bold :foreground "#000000" :background "#44423c"))))
   `(diff-hl-dired-insert ((,class (:weight bold :foreground "#444445"))))
   `(diff-hl-dired-unknown ((,class (:foreground "#000000" :background "#413cba"))))
   `(diff-hl-insert ((,class (:foreground "#009a00" :inherit diff-added))))
   `(diff-hl-unknown ((,class (:foreground "#000000" :background "#413cba"))))
   `(diary-face ((,class (:foreground "#223340"))))
   `(dircolors-face-asm ((,class (:foreground "#ffffff"))))
   `(dircolors-face-backup ((,class (:foreground "#ffffff"))))
   `(dircolors-face-compress ((,class (:foreground "#c90000"))))
   `(dircolors-face-dir ((,class ,directory)))
   `(dircolors-face-doc ((,class (:foreground "#ffffff"))))
   `(dircolors-face-dos ((,class (:foreground "#239123"))))
   `(dircolors-face-emacs ((,class (:foreground "#ffffff"))))
   `(dircolors-face-exec ((,class (:foreground "#239123"))))
   `(dircolors-face-html ((,class (:foreground "#ffffff"))))
   `(dircolors-face-img ((,class (:foreground "#c500c5"))))
   `(dircolors-face-lang ((,class (:foreground "#ffffff"))))
   `(dircolors-face-lang-interface ((,class (:foreground "#ffffff"))))
   `(dircolors-face-make ((,class (:foreground "#ffffff"))))
   `(dircolors-face-objet ((,class (:foreground "#ffffff"))))
   `(dircolors-face-package ((,class (:foreground "#ffffff"))))
   `(dircolors-face-paddb ((,class (:foreground "#ffffff"))))
   `(dircolors-face-ps ((,class (:foreground "#ffffff"))))
   `(dircolors-face-sound ((,class (:foreground "#004a63"))))
   `(dircolors-face-tar ((,class (:foreground "#c90000"))))
   `(dircolors-face-text ((,class (:foreground "#ffffff"))))
   `(dircolors-face-yacc ((,class (:foreground "#ffffff"))))
   `(dired-directory ((,class ,directory)))
   `(dired-header ((,class ,directory)))
   `(dired-ignored ((,class (:strike-through t :foreground "#c90000"))))
   `(dired-mark ((,class ,marked-line)))
   `(dired-marked ((,class ,marked-line)))
   `(dired-symlink ((,class ,symlink)))
   `(diredp-compressed-file-suffix ((,class (:foreground "#c90000"))))
   `(diredp-date-time ((,class (:foreground "#7818b5"))))
   `(diredp-dir-heading ((,class ,directory)))
   `(diredp-dir-name ((,class ,directory)))
   `(diredp-dir-priv ((,class ,directory)))
   `(diredp-exec-priv ((,class (:background "#016f22"))))
   `(diredp-executable-tag ((,class (:foreground "#239123" :background "#000000"))))
   `(diredp-file-name ((,class ,file)))
   `(diredp-file-suffix ((,class (:foreground "#3f3f3f"))))
   `(diredp-flag-mark-line ((,class ,marked-line)))
   `(diredp-ignored-file-name ((,class ,shadow)))
   `(diredp-read-priv ((,class (:background "#044a7c"))))
   `(diredp-write-priv ((,class (:foreground "#000000" :background "#962525"))))
   `(elfeed-search-filter-face ((,class (:foreground "#414141"))))
   ;; `(eww-form-checkbox ((,class ())))
   ;; `(eww-form-select ((,class ())))
   ;; `(eww-form-submit ((,class ())))
   `(eww-form-text ((,class (:weight bold :foreground "#6286aa" :background "#262e37"))))
   ;; `(eww-form-textarea ((,class ())))
   `(file-name-shadow ((,class ,shadow)))
   `(font-latex-bold-face ((,class (:weight bold :foreground "#ffffff"))))
   `(fancy-narrow-blocked-face ((,class (:foreground "#5e5d65"))))
   `(flycheck-color-mode-line-error-face ((, class (:background "#972525"))))
   `(flycheck-color-mode-line-warning-face ((, class (:background "#523500"))))
   `(flycheck-color-mode-line-info-face ((, class (:background "#111100"))))
   `(font-latex-italic-face ((,class (:slant italic :foreground "#e5e5e5"))))
   `(font-latex-math-face ((,class (:foreground "#0000ed"))))
   `(font-latex-sectioning-1-face ((,class (:family "Sans Serif" :height 2.7 :weight bold :foreground "#2e456e"))))
   `(font-latex-sectioning-2-face ((,class ,ol1)))
   `(font-latex-sectioning-3-face ((,class ,ol2)))
   `(font-latex-sectioning-4-face ((,class ,ol3)))
   `(font-latex-sectioning-5-face ((,class ,ol4)))
   `(font-latex-sedate-face ((,class (:foreground "#8c2e00"))))
   `(font-latex-string-face ((,class (:weight bold :foreground "#0041a3"))))
   `(font-latex-verbatim-face ((,class (:foreground "#0000f5" :background "#020201" :inherit nil))))
   `(git-commit-summary-face ((,class (:foreground "#ffffff"))))
   `(git-commit-comment-face ((,class (:slant italic :foreground "#969696"))))
   `(google-translate-text-face ((,class (:foreground "#888888" :background "#0a0a0a"))))
   `(google-translate-phonetic-face ((,class (:inherit shadow))))
   `(google-translate-translation-face ((,class (:weight normal :foreground "#1c478d" :background "#131415"))))
   `(google-translate-suggestion-label-face ((,class (:foreground "#c90000"))))
   `(google-translate-suggestion-face ((,class (:slant italic :underline t))))
   `(google-translate-listen-button-face ((,class (:height 0.8))))
   `(helm-action ((,class (:foreground "#ffffff"))))
   `(helm-bookmark-file ((,class ,file)))
   `(helm-bookmarks-su-face ((,class (:foreground "#c90000"))))
   `(helm-buffer-directory ((,class ,directory)))
   `(helm-buffer-process ((,class (:foreground "#00a100"))))
   `(helm-candidate-number ((,class (:foreground "#ffffff" :background "#0a0a04"))))
   `(helm-dir-heading ((,class (:foreground "#0000ed" :background "#302426"))))
   `(helm-dir-priv ((,class (:foreground "#e10000" :background "#2c2c2c"))))
   `(helm-ff-directory ((,class ,directory)))
   `(helm-ff-dotted-directory ((,class ,directory)))
   `(helm-ff-executable ((,class (:foreground "#006b00" :background "#000000"))))
   `(helm-ff-file ((,class (:foreground "#ffffff"))))
   `(helm-ff-invalid-symlink ((,class (:foreground "#111100" :background "#c90000"))))
   `(helm-ff-symlink ((,class ,symlink)))
   `(helm-file-name ((,class (:foreground "#0000ed"))))
   `(helm-gentoo-match-face ((,class (:foreground "#c90000"))))
   `(helm-grep-lineno ((,class ,shadow)))
   `(helm-grep-match ((,class ,match)))
   `(helm-grep-running ((,class (:weight bold :foreground "#000000"))))
   `(helm-isearch-match ((,class (:background "#0b0e0b"))))
   `(helm-lisp-show-completion ((,class ,volatile-highlight))) ; See `helm-dabbrev'.
   ;; `(helm-ls-git-added-copied-face ((,class (:foreground ""))))
   ;; `(helm-ls-git-added-modified-face ((,class (:foreground ""))))
   ;; `(helm-ls-git-conflict-face ((,class (:foreground ""))))
   ;; `(helm-ls-git-deleted-and-staged-face ((,class (:foreground ""))))
   ;; `(helm-ls-git-deleted-not-staged-face ((,class (:foreground ""))))
   ;; `(helm-ls-git-modified-and-staged-face ((,class (:foreground ""))))
   `(helm-ls-git-modified-not-staged-face ((,class (:foreground "#a52f92"))))
   ;; `(helm-ls-git-renamed-modified-face ((,class (:foreground ""))))
   ;; `(helm-ls-git-untracked-face ((,class (:foreground ""))))
   `(helm-match ((,class ,match)))
   `(helm-moccur-buffer ((,class (:foreground "#0053a7"))))
   `(helm-selection ((,class ,highlight-blue)))
   `(helm-selection-line ((,class ,highlight-gray)))
   `(helm-separator ((,class (:foreground "#c90000"))))
   `(helm-source-header ((,class ,ol1)))
   `(helm-swoop-target-line-block-face ((,class (:background "#414100" :foreground "#dddddd"))))
   `(helm-swoop-target-line-face ((,class ,volatile-highlight)))
   `(helm-swoop-target-word-face ((,class (:weight bold :foreground nil :background "#3e2e0c"))))
   `(helm-visible-mark ((,class ,marked-line)))
   `(helm-w3m-bookmarks-face ((,class (:underline t :foreground "#003535"))))
   `(highlight-changes ((,class (:foreground nil)))) ;; blue "#3909e2"
   `(highlight-changes-delete ((,class (:strike-through nil :foreground nil)))) ;; red "#d00934"
   `(highlight-symbol-face ((,class (:background "#060603"))))
   `(hl-line ((,class ,highlight-green))) ; Highlight current line.
   `(hl-tags-face ((,class ,highlight-current-tag))) ; ~ Pair highlighting (matching tags).
   `(holiday-face ((,class (:foreground "#888888" :background "#111214"))))
   `(html-helper-bold-face ((,class (:weight bold :foreground "#ffffff"))))
   `(html-helper-italic-face ((,class (:slant italic :foreground "#ffffff"))))
   `(html-helper-underline-face ((,class (:underline t :foreground "#ffffff"))))
   `(html-tag-face ((,class (:foreground "#0000ed"))))
   `(ilog-non-change-face ((,class (:height 2.0 :foreground "#713bb9"))))
   `(ilog-change-face ((,class (:height 2.0 :foreground "#00a100"))))
   `(ilog-echo-face ((,class (:height 2.0 :foreground "#004e9f"))))
   `(ilog-load-face ((,class (:foreground "#a52f92"))))
   `(ilog-message-face ((,class (:foreground "#7f7f7f"))))
   `(indent-guide-face ((,class (:foreground "#2c2c2c"))))
   `(info-file ((,class (:family "Sans Serif" :height 1.8 :weight bold :box (:line-width 1 :color "#0000f0") :foreground "#2e456e" :background "#191c20"))))
   `(info-header-node ((,class (:underline t :foreground "#523500")))) ; nodes in header
   `(info-header-xref ((,class (:underline t :foreground "#0e477f")))) ; cross references in header
   `(info-index-match ((,class (:weight bold :foreground nil :background "#3e2e0c")))) ; when using `i'
   `(info-menu-header ((,class ,ol2))) ; menu titles (headers) -- major topics
   `(info-menu-star ((,class (:foreground "#ffffff")))) ; every 3rd menu item
   `(info-node ((,class (:underline t :foreground "#0000ed")))) ; node names
   `(info-quoted-name ((,class ,code-inline)))
   `(info-string ((,class ,string)))
   `(info-title-1 ((,class ,ol1)))
   `(info-xref ((,class (:underline t :foreground "#0066a4")))) ; unvisited cross-references
   `(info-xref-visited ((,class (:underline t :foreground "#d800d8")))) ; previously visited cross-references
   ;; js2-highlight-vars-face (~ auto-highlight-symbol)
   `(js2-function-param ((,class (:foreground "#242113"))))
   `(js2-error ((,class (:box (:line-width 1 :color "#9e2222") :background "#171414")))) ; DONE.
   `(js2-external-variable ((,class (:foreground "#c90000")))) ; DONE.
   `(js2-function-param ((,class (:foreground "#2e8b57"))))
   `(js2-instance-member ((,class (:foreground "#802aac"))))
   `(js2-jsdoc-html-tag-delimiter ((,class (:foreground "#004700"))))
   `(js2-jsdoc-html-tag-name ((,class (:foreground "#111100"))))
   `(js2-jsdoc-tag ((,class (:foreground "#647281"))))
   `(js2-jsdoc-type ((,class (:foreground "#346086"))))
   `(js2-jsdoc-value ((,class (:foreground "#4b4036"))))
   `(js2-magic-paren ((,class (:underline t))))
   `(js2-private-function-call ((,class (:foreground "#58420c"))))
   `(js2-private-member ((,class (:foreground "#4b4036"))))
   `(js2-warning ((,class (:underline "#523500"))))

   ;; Org non-standard faces.
   `(leuven-org-deadline-overdue ((,class (:foreground "#aa1a3e"))))
   `(leuven-org-deadline-today ((,class (:weight bold :foreground "#b4a88a" :background "#030302"))))
   `(leuven-org-deadline-tomorrow ((,class (:foreground "#2d7707"))))
   `(leuven-org-deadline-future ((,class (:foreground "#2d7707"))))
   `(leuven-gnus-unseen ((,class (:weight bold :foreground "#773500"))))
   `(leuven-gnus-date ((,class (:foreground "#5f2f47"))))
   `(leuven-gnus-size ((,class (:foreground "#3b5028"))))

   `(light-symbol-face ((,class (:background "#060603"))))
   `(linum ((,class (:foreground "#656565" :background "#121212"))))
   `(log-view-file ((,class (:foreground "#0000f0" :background "#0d0d0e"))))
   `(log-view-message ((,class (:foreground "#404000"))))
   `(lui-button-face ((,class ,link)))
   `(lui-highlight-face ((,class (:box '(:line-width 1 :color "#d40000") :foreground "#d40000" :background "#080804")))) ; my nickname
   `(lui-time-stamp-face ((,class (:foreground "#7818b5"))))
   `(magit-blame-header ((,class (:inherit magit-diff-file-header))))
   `(magit-blame-heading ((,class (:overline "#585858" :foreground "#c90000" :background "#191919"))))
   `(magit-blame-hash ((,class (:overline "#585858" :foreground "#c90000" :background "#191919"))))
   `(magit-blame-name ((,class (:overline "#585858" :foreground "#05b10b" :background "#191919"))))
   `(magit-blame-date ((,class (:overline "#585858" :foreground "#0000ed" :background "#191919"))))
   `(magit-blame-summary ((,class (:overline "#585858" :weight bold :foreground "#8f8f8f" :background "#191919"))))
   `(magit-branch ((,class ,vc-branch)))
   `(magit-diff-add ((,class ,diff-added)))
   `(magit-diff-del ((,class ,diff-removed)))
   `(magit-diff-file-header ((,class (:height 1.1 :weight bold :foreground "#2c5885"))))
   `(magit-diff-hunk-header ((,class ,diff-hunk-header)))
   `(magit-diff-none ((,class ,diff-none)))
   `(magit-header ((,class (:foreground "#000000" :background "#962525"))))
   `(magit-item-highlight ((,class (:background "#0d0d0e"))))
   `(magit-item-mark ((,class ,marked-line)))
   `(magit-log-head-label ((,class (:box (:line-width 1 :color "#0000ed" :style nil)))))
   `(magit-log-tag-label ((,class (:box (:line-width 1 :color "#006c00" :style nil)))))
   `(magit-section-title ((,class (:family "Sans Serif" :height 1.8 :weight bold :foreground "#2e456e" :inherit nil))))
   `(makefile-space-face ((,class (:background "#712e4f"))))
   `(makefile-targets ((,class (:weight bold :foreground "#0000ed"))))
   ;; `(markdown-blockquote-face ((,class ())))
   `(markdown-bold-face ((,class (:inherit bold))))
   ;; `(markdown-comment-face ((,class ())))
   ;; `(markdown-footnote-face ((,class ())))
   ;; `(markdown-header-delimiter-face ((,class ())))
   ;; `(markdown-header-face ((,class ())))
   `(markdown-header-face-1 ((,class ,ol1)))
   `(markdown-header-face-2 ((,class ,ol2)))
   `(markdown-header-face-3 ((,class ,ol3)))
   `(markdown-header-face-4 ((,class ,ol4)))
   `(markdown-header-face-5 ((,class ,ol5)))
   `(markdown-header-face-6 ((,class ,ol6)))
   ;; `(markdown-header-rule-face ((,class ())))
   `(markdown-inline-code-face ((,class ,code-inline)))
   `(markdown-italic-face ((,class (:inherit italic))))
   ;; `(markdown-language-keyword-face ((,class ())))
   ;; `(markdown-line-break-face ((,class ())))
   `(markdown-link-face ((,class ,link-no-underline)))
   ;; `(markdown-link-title-face ((,class ())))
   ;; `(markdown-list-face ((,class ())))
   ;; `(markdown-math-face ((,class ())))
   ;; `(markdown-metadata-key-face ((,class ())))
   ;; `(markdown-metadata-value-face ((,class ())))
   ;; `(markdown-missing-link-face ((,class ())))
   ;; `(markdown-pre-face ((,class ())))
   ;; `(markdown-reference-face ((,class ())))
   ;; `(markdown-strike-through-face ((,class ())))
   `(markdown-url-face ((,class ,link)))
   `(match ((,class ,match)))           ; Used for grep matches.
   `(mc/cursor-bar-face ((,class (:height 1.0 :foreground "#000000" :background "#1253a4"))))
   `(mc/cursor-face ((,class (:inverse-video t))))
   `(mc/region-face ((,class (:inherit region))))
   `(mm-uu-extract ((,class ,code-block)))
   `(moccur-current-line-face ((,class (:foreground "#ffffff" :background "#030302"))))
   `(moccur-face ((,class (:foreground "#ffffff" :background "#070704"))))
   `(next-error ((,class ,volatile-highlight)))
   `(nobreak-space ((,class (:background "#16191b"))))
   `(nxml-attribute-local-name-face ((,class ,xml-attribute)))
   `(nxml-attribute-value-delimiter-face ((,class (:foreground "#009a00"))))
   `(nxml-attribute-value-face ((,class (:foreground "#009a00"))))
   `(nxml-comment-content-face ((,class (:slant italic :foreground "#c90000"))))
   `(nxml-comment-delimiter-face ((,class (:foreground "#c90000"))))
   `(nxml-element-local-name ((,class ,xml-tag)))
   `(nxml-element-local-name-face ((,class (:foreground "#0000ed"))))
   `(nxml-processing-instruction-target-face ((,class (:foreground "#6720aa"))))
   `(nxml-tag-delimiter-face ((,class (:foreground "#0000ed"))))
   `(nxml-tag-slash-face ((,class (:foreground "#0000ed"))))
   `(org-agenda-block-count ((,class (:weight bold :foreground "#5a5a5a"))))
   `(org-agenda-calendar-event ((,class (:weight bold :foreground "#275291" :background "#111214"))))
   `(org-agenda-calendar-sexp ((,class (:foreground "#22548e" :background "#070708"))))
   `(org-agenda-clocking ((,class (:foreground "#ffffff" :background "#3c3200"))))
   `(org-agenda-column-dateline ((,class ,column)))
   `(org-agenda-current-time ((,class (:underline t :foreground "#145da7"))))
   `(org-agenda-date ((,class (:height 1.6 :weight bold :foreground "#145da7"))))
   `(org-agenda-date-today ((,class (:height 1.6 :weight bold :foreground "#b4a88a" :background "#030302"))))
   `(org-agenda-date-weekend ((,class (:height 1.6 :weight bold :foreground "#b1b1b1"))))
   `(org-agenda-diary ((,class (:weight bold :foreground "#009a00" :background "#232c2f"))))
   `(org-agenda-dimmed-todo-face ((,class (:foreground "#3c3200"))))
   `(org-agenda-done ((,class (:foreground "#aaaaaa"))))
   `(org-agenda-filter-category ((,class (:weight bold :foreground "#523500"))))
   `(org-agenda-filter-tags ((,class (:weight bold :foreground "#523500"))))
   `(org-agenda-restriction-lock ((,class (:background "#6d3a2e"))))
   `(org-agenda-structure ((,class (:height 1.6 :weight bold :foreground "#125683"))))
   `(org-archived ((,class (:foreground "#4c4c4c"))))
   `(org-beamer-tag ((,class (:box (:line-width 1 :color "#413006") :foreground "#d3d3d3" :background "#080706"))))
   `(org-block ((,class ,code-block)))
   `(org-block-background ((,class (:background "#020201")))) ;; :inherit fixed-pitch))))
   `(org-block-begin-line ((,class (:underline "#565558" :foreground "#aaaaaa" :background "#1e1d1c"))))
   `(org-block-end-line ((,class (:overline "#565558" :foreground "#aaaaaa" :background "#1e1d1c"))))
   `(org-checkbox ((,class (:weight bold :box (:line-width 1 :style pressed-button) :foreground "#bcbcbc" :background "#5c5c5c"))))
   `(org-clock-overlay ((,class (:foreground "#000000" :background "#4f7895"))))
   `(org-code ((,class ,code-inline)))
   `(org-column ((,class ,column)))
   `(org-column-title ((,class ,column)))
   `(org-date ((,class (:underline t :foreground "#0054c2"))))
   `(org-default ((,class (:foreground "#cccccc" :background "#000000"))))
   `(org-dim ((,class (:foreground "#555555"))))
   `(org-document-info ((,class (:foreground "#b7b7b7"))))
   `(org-document-info-keyword ((,class (:foreground "#005d8a" :background "#111113"))))
   `(org-document-title ((,class (:family "Sans Serif" :height 1.8 :weight bold :foreground "#ffffff"))))
   `(org-done ((,class (:weight bold :box (:line-width 1 :color "#444444") :foreground "#444444" :background "#0f0f0f"))))
   `(org-drawer ((,class (:foreground "#20313c"))))
   `(org-ellipsis ((,class (:underline nil :box (:line-width 1 :color "#666666") :foreground "#666666" :background "#090806")))) ; #171508
   `(org-example ((,class (:foreground "#0000ed" :background "#040504"))))
   `(org-footnote ((,class (:underline t :foreground "#005d8a"))))
   `(org-formula ((,class (:foreground "#6b350f"))))
   `(org-headline-done ((,class (:height 1.0 :weight normal :strike-through t :foreground "#525252"))))
   `(org-hide ((,class (:foreground "#1d1d1d"))))
   `(org-inlinetask ((,class (:box (:line-width 1 :color "#141414") :foreground "#888888" :background "#020201"))))
   `(org-latex-and-related ((,class (:foreground "#356aa0" :background "#000000"))))
   `(org-level-1 ((,class ,ol1)))
   `(org-level-2 ((,class ,ol2)))
   `(org-level-3 ((,class ,ol3)))
   `(org-level-4 ((,class ,ol4)))
   `(org-level-5 ((,class ,ol5)))
   `(org-level-6 ((,class ,ol6)))
   `(org-level-7 ((,class ,ol7)))
   `(org-level-8 ((,class ,ol8)))
   `(org-link ((,class ,link)))
   `(org-list-dt ((,class (:weight bold :foreground "#315ba4"))))
   `(org-macro ((,class (:weight bold :foreground "#483700"))))
   `(org-meta-line ((,class (:slant normal :foreground "#005d8a" :background "#111113"))))
   `(org-mode-line-clock ((,class (:box (:line-width 1 :color "#315ba4") :foreground "#ffffff" :background "#503310"))))
   `(org-mode-line-clock-overrun ((,class (:weight bold :box (:line-width 1 :color "#315ba4") :foreground "#000000" :background "#962525"))))
   `(org-number-of-items ((,class (:weight bold :foreground "#000000" :background "#385738"))))
   `(org-property-value ((,class (:foreground "#008b00"))))
   `(org-quote ((,class (:slant italic :foreground "#969696" :background "#020201"))))
   `(org-scheduled ((,class (:foreground "#cccccc"))))
   `(org-scheduled-previously ((,class (:foreground "#1053a3"))))
   `(org-scheduled-today ((,class (:weight bold :foreground "#b4a88a" :background "#030302"))))
   `(org-sexp-date ((,class (:foreground "#275291"))))
   `(org-special-keyword ((,class (:weight bold :foreground "#007800" :background "#040504"))))
   `(org-table ((,class (:foreground "#00b700" :background "#040504")))) ;; :inherit fixed-pitch))))
   `(org-tag ((,class (:weight normal :slant italic :foreground "#5a5d60" :background "#000000"))))
   `(org-target ((,class (:foreground "#6e2f4b"))))
   `(org-time-grid ((,class (:foreground "#303030"))))
   `(org-todo ((,class (:weight bold :box (:line-width 1 :color "#4a3a39") :foreground "#4a3a39" :background "#131110"))))
   `(org-upcoming-deadline ((,class (:foreground "#862c2c"))))
   `(org-verbatim ((,class (:foreground "#0053a7" :background "#020203"))))
   `(org-verse ((,class (:slant italic :foreground "#969696" :background "#111111"))))
   `(org-warning ((,class (:weight bold :foreground "#ffffff" :background "#15181b"))))
   `(outline-1 ((,class ,ol1)))
   `(outline-2 ((,class ,ol2)))
   `(outline-3 ((,class ,ol3)))
   `(outline-4 ((,class ,ol4)))
   `(outline-5 ((,class ,ol5)))
   `(outline-6 ((,class ,ol6)))
   `(outline-7 ((,class ,ol7)))
   `(outline-8 ((,class ,ol8)))
   `(pabbrev-debug-display-label-face ((,class (:background "#152c00"))))
   `(pabbrev-suggestions-face ((,class (:weight bold :foreground "#000000" :background "#c90000"))))
   `(pabbrev-suggestions-label-face ((,class (:weight bold :foreground "#000000" :background "#7818b5"))))
   `(paren-face-match ((,class ,paren-matched)))
   `(paren-face-mismatch ((,class ,paren-unmatched)))
   `(paren-face-no-match ((,class ,paren-unmatched)))
   `(persp-selected-face ((,class (:weight bold :foreground "#09090a"))))
   `(powerline-active1 ((,class (:foreground "#23363e" :background "#c7c7c7" :inherit mode-line))))
   `(powerline-active2 ((,class (:foreground "#23363e" :background "#345b94" :inherit mode-line))))
   `(powerline-inactive1 ((,class (:foreground "#0f0f0e" :background "#979797" :inherit mode-line-inactive))))
   `(powerline-inactive2 ((,class (:foreground "#0f0f0e" :background "#565656" :inherit mode-line-inactive))))
   `(rainbow-delimiters-depth-1-face ((,class (:foreground "#77788c"))))
   `(rainbow-delimiters-depth-2-face ((,class (:foreground "#3e4a75"))))
   `(rainbow-delimiters-depth-3-face ((,class (:foreground "#6e6f64"))))
   `(rainbow-delimiters-depth-4-face ((,class (:foreground "#547254"))))
   `(rainbow-delimiters-depth-5-face ((,class (:foreground "#856a6a"))))
   `(rainbow-delimiters-depth-6-face ((,class (:foreground "#475688"))))
   `(rainbow-delimiters-depth-7-face ((,class (:foreground "#7a7a75"))))
   `(rainbow-delimiters-depth-8-face ((,class (:foreground "#4a624a"))))
   `(rainbow-delimiters-depth-9-face ((,class (:foreground "#897070"))))
   `(rainbow-delimiters-mismatched-face ((,class ,paren-unmatched)))
   `(rainbow-delimiters-unmatched-face ((,class ,paren-unmatched)))
   `(recover-this-file ((,class (:weight bold :background "#972525"))))
   `(rng-error ((,class (:weight bold :foreground "#c90000" :background "#161313"))))
   `(sh-heredoc ((,class (:foreground "#0000ed" :background "#09090a"))))
   `(sh-quoted-exec ((,class (:foreground "#b00d65"))))
   `(shadow ((,class ,shadow)))         ; Used for grep context lines.
   `(shell-option-face ((,class (:foreground "#239123"))))
   `(shell-output-2-face ((,class (:foreground "#0000ed"))))
   `(shell-output-3-face ((,class (:foreground "#7818b5"))))
   `(shell-output-face ((,class (:foreground "#ffffff"))))
   ;; `(shell-prompt-face ((,class (:weight bold :foreground "#111100"))))
   `(shm-current-face ((,class (:background "#171614"))))
   `(shm-quarantine-face ((,class (:background "lemonchiffon"))))
   `(show-paren-match ((,class ,paren-matched)))
   `(show-paren-mismatch ((,class ,paren-unmatched)))
   `(sml-modeline-end-face ((,class (:background "#273f5a")))) ; #315ba4
   `(sml-modeline-vis-face ((,class (:background "#125894"))))

   ;; `(sp-pair-overlay-face                        
   ;; `(sp-show-pair-enclosing                      
   ;; `(sp-show-pair-match-face                      ; ~ Pair highlighting (matching tags).
   ;; `(sp-show-pair-mismatch-face                  
   ;; `(sp-wrap-overlay-closing-pair                
   ;; `(sp-wrap-overlay-face                        
   ;; `(sp-wrap-overlay-opening-pair                
   ;; `(sp-wrap-tag-overlay-face                    

   `(speedbar-button-face ((,class (:foreground "#009a00"))))
   `(speedbar-directory-face ((,class (:foreground "#0000f5"))))
   `(speedbar-file-face ((,class (:foreground "#009191"))))
   `(speedbar-highlight-face ((,class ,volatile-highlight)))
   `(speedbar-selected-face ((,class (:underline t :foreground "#c90000"))))
   `(speedbar-tag-face ((,class (:foreground "#bb2f2f"))))
   `(svn-status-directory-face ((,class ,directory)))
   `(svn-status-filename-face ((,class (:weight bold :foreground "#2c5885"))))
   `(svn-status-locked-face ((,class (:weight bold :foreground "#c90000"))))
   `(svn-status-marked-face ((,class ,marked-line)))
   `(svn-status-marked-popup-face ((,class (:weight bold :foreground "#006b00"))))
   `(svn-status-switched-face ((,class (:slant italic :foreground "#737373"))))
   `(svn-status-symlink-face ((,class ,symlink)))
   `(svn-status-update-available-face ((,class (:foreground "#523500"))))
   `(tex-verbatim ((,class (:foreground "#0000ed"))))
   `(tool-bar ((,class (:box (:line-width 1 :style released-button) :foreground "#ffffff" :background "#404040"))))
   `(tooltip ((,class (:foreground "#ffffff" :background "#020201"))))
   `(trailing-whitespace ((,class (:background "#0f0e10"))))
   `(traverse-match-face ((,class (:weight bold :foreground "#6d22b3"))))
   `(vc-annotate-face-3F3FFF ((,class (:foreground "#2b2bb2" :background "#ffffff"))))
   `(vc-annotate-face-3F6CFF ((,class (:foreground "#2b2bb2" :background "#ffffff"))))
   `(vc-annotate-face-3F99FF ((,class (:foreground "#1b4371" :background "#ffffff"))))
   `(vc-annotate-face-3FC6FF ((,class (:foreground "#1b4371" :background "#ffffff"))))
   `(vc-annotate-face-3FF3FF ((,class (:foreground "#0b2d30" :background "#ffffff"))))
   `(vc-annotate-face-3FFF56 ((,class (:foreground "#0e320e" :background "#ffffff"))))
   `(vc-annotate-face-3FFF83 ((,class (:foreground "#0b2d1f" :background "#ffffff"))))
   `(vc-annotate-face-3FFFB0 ((,class (:foreground "#0b2d1f" :background "#ffffff"))))
   `(vc-annotate-face-3FFFDD ((,class (:foreground "#0b2d30" :background "#ffffff"))))
   `(vc-annotate-face-56FF3F ((,class (:foreground "#0e320e" :background "#ffffff"))))
   `(vc-annotate-face-83FF3F ((,class (:foreground "#141e07" :background "#ffffff"))))
   `(vc-annotate-face-B0FF3F ((,class (:foreground "#141e07" :background "#ffffff"))))
   `(vc-annotate-face-DDFF3F ((,class (:foreground "#161405" :background "#ffffff"))))
   `(vc-annotate-face-F6FFCC ((,class (:foreground "#ffffff" :background "#040403"))))
   `(vc-annotate-face-FF3F3F ((,class (:foreground "#972525" :background "#ffffff"))))
   `(vc-annotate-face-FF6C3F ((,class (:foreground "#972525" :background "#ffffff"))))
   `(vc-annotate-face-FF993F ((,class (:foreground "#563315" :background "#ffffff"))))
   `(vc-annotate-face-FFC63F ((,class (:foreground "#563315" :background "#ffffff"))))
   `(vc-annotate-face-FFF33F ((,class (:foreground "#161405" :background "#ffffff"))))
   `(vhl/default-face ((,class ,volatile-highlight))) ; `volatile-highlights.el'.
   `(w3m-anchor ((,class ,link)))
   `(w3m-arrived-anchor ((,class (:foreground "#6720aa"))))
   `(w3m-bitmap-image-face ((,class (:foreground "#f5f5f5" :background "#004700"))))
   `(w3m-bold ((,class (:weight bold :foreground "#ffffff"))))
   `(w3m-current-anchor ((,class (:weight bold :underline t :foreground "#0000ed"))))
   `(w3m-form ((,class (:underline t :foreground "#4d3117"))))
   `(w3m-form-button-face ((,class (:weight bold :underline t :foreground "#f5f5f5" :background "#2c2c2c"))))
   `(w3m-form-button-mouse-face ((,class (:underline t :foreground "#2c2c2c" :background "#339832"))))
   `(w3m-form-button-pressed-face ((,class (:weight bold :underline t :foreground "#f5f5f5" :background "#2c2c2c"))))
   `(w3m-header-line-location-content-face ((,class (:foreground "#808080":background "#080808"))))
   `(w3m-header-line-location-title-face ((,class (:foreground "#2a52ac" :background "#080808"))))
   `(w3m-history-current-url-face ((,class (:foreground "#070605"))))
   `(w3m-image-face ((,class (:weight bold :foreground "#182118"))))
   `(w3m-link-numbering ((,class (:foreground "#2b3039")))) ; mouseless browsing
   `(w3m-strike-through-face ((,class (:strike-through t))))
   `(w3m-underline-face ((,class (:underline t))))

   ;; `(web-mode-block-attr-name-face ((,class ())))
   ;; `(web-mode-block-attr-value-face ((,class ())))
   ;; `(web-mode-block-comment-face ((,class ())))
   ;; `(web-mode-block-control-face ((,class ())))
   ;; `(web-mode-block-delimiter-face ((,class ())))
   ;; `(web-mode-block-face ((,class ())))
   ;; `(web-mode-block-string-face ((,class ())))
   ;; `(web-mode-bold-face ((,class ())))
   ;; `(web-mode-builtin-face ((,class ())))
   ;; `(web-mode-comment-face ((,class ())))
   ;; `(web-mode-comment-keyword-face ((,class ())))
   ;; `(web-mode-constant-face ((,class ())))
   ;; `(web-mode-css-at-rule-face ((,class ())))
   ;; `(web-mode-css-color-face ((,class ())))
   ;; `(web-mode-css-comment-face ((,class ())))
   ;; `(web-mode-css-function-face ((,class ())))
   ;; `(web-mode-css-priority-face ((,class ())))
   ;; `(web-mode-css-property-name-face ((,class ())))
   ;; `(web-mode-css-pseudo-class-face ((,class ())))
   ;; `(web-mode-css-selector-face ((,class ())))
   ;; `(web-mode-css-string-face ((,class ())))
   ;; `(web-mode-css-variable-face ((,class ())))
   ;; `(web-mode-current-column-highlight-face ((,class ())))
   `(web-mode-current-element-highlight-face ((,class (:background "#47345f")))) ; #15130a
   ;; `(web-mode-doctype-face ((,class ())))
   ;; `(web-mode-error-face ((,class ())))
   ;; `(web-mode-filter-face ((,class ())))
   ;; `(web-mode-folded-face ((,class ())))
   ;; `(web-mode-function-call-face ((,class ())))
   ;; `(web-mode-function-name-face ((,class ())))
   ;; `(web-mode-html-attr-custom-face ((,class ())))
   ;; `(web-mode-html-attr-engine-face ((,class ())))
   ;; `(web-mode-html-attr-equal-face ((,class ())))
   `(web-mode-html-attr-name-face ((,class ,xml-attribute)))
   ;; `(web-mode-html-attr-value-face ((,class ())))
   ;; `(web-mode-html-entity-face ((,class ())))
   `(web-mode-html-tag-bracket-face ((,class ,xml-tag)))
   ;; `(web-mode-html-tag-custom-face ((,class ())))
   `(web-mode-html-tag-face ((,class ,xml-tag)))
   ;; `(web-mode-html-tag-namespaced-face ((,class ())))
   ;; `(web-mode-inlay-face ((,class ())))
   ;; `(web-mode-italic-face ((,class ())))
   ;; `(web-mode-javascript-comment-face ((,class ())))
   ;; `(web-mode-javascript-string-face ((,class ())))
   ;; `(web-mode-json-comment-face ((,class ())))
   ;; `(web-mode-json-context-face ((,class ())))
   ;; `(web-mode-json-key-face ((,class ())))
   ;; `(web-mode-json-string-face ((,class ())))
   ;; `(web-mode-jsx-depth-1-face ((,class ())))
   ;; `(web-mode-jsx-depth-2-face ((,class ())))
   ;; `(web-mode-jsx-depth-3-face ((,class ())))
   ;; `(web-mode-jsx-depth-4-face ((,class ())))
   ;; `(web-mode-keyword-face ((,class ())))
   ;; `(web-mode-param-name-face ((,class ())))
   ;; `(web-mode-part-comment-face ((,class ())))
   `(web-mode-part-face ((,class (:background "#020201"))))
   ;; `(web-mode-part-string-face ((,class ())))
   ;; `(web-mode-preprocessor-face ((,class ())))
   `(web-mode-script-face ((,class (:background "#0e0e0f"))))
   ;; `(web-mode-sql-keyword-face ((,class ())))
   ;; `(web-mode-string-face ((,class ())))
   ;; `(web-mode-style-face ((,class ())))
   ;; `(web-mode-symbol-face ((,class ())))
   ;; `(web-mode-type-face ((,class ())))
   ;; `(web-mode-underline-face ((,class ())))
   ;; `(web-mode-variable-name-face ((,class ())))
   ;; `(web-mode-warning-face ((,class ())))
   ;; `(web-mode-whitespace-face ((,class ())))

   `(which-func ((,class (:weight bold :foreground "#000000"))))
   ;; `(which-key-command-description-face)
   ;; `(which-key-group-description-face)
   ;; `(which-key-highlighted-command-face)
   ;; `(which-key-key-face)
   `(which-key-local-map-description-face ((,class (:weight bold :background "#070708" :inherit which-key-command-description-face))))
   ;; `(which-key-note-face)
   ;; `(which-key-separator-face)
   ;; `(which-key-special-key-face)
   `(widget-button ((,class ,link)))
   `(widget-button-pressed ((,class (:foreground "#c90000"))))
   `(widget-documentation ((,class (:foreground "#009a00"))))
   `(widget-field ((,class (:background "#262626"))))
   `(widget-inactive ((,class (:foreground "#969696"))))
   `(widget-single-line-field ((,class (:background "#262626"))))
   `(woman-bold ((,class (:weight bold :foreground "#9c2727"))))
   `(woman-italic ((,class (:weight bold :slant italic :foreground "#25650e"))))
   `(woman-symbol ((,class (:weight bold :foreground "#7818b5"))))
   `(yas-field-debug-face ((,class (:background "#c90000"))))
   `(yas-field-highlight-face ((,class (:box (:line-width 1 :color "#7c7c7c") :foreground "#ffffff" :background "#222423"))))
   ))

(custom-theme-set-variables 'leuven

  ;; highlight-sexp-mode.
  '(hl-sexp-background-color "#131212")

  '(ansi-color-faces-vector
    [default default default italic underline success warning error])

  ;; Colors used in Shell mode.
  '(ansi-color-names-vector
    ["#ffffff" "#d30000" "#239123" "#404000" "#0000ed" "#c500c5" "#004a63" "#808080"])
 )

;;;######autoload
(when (and (boundp 'custom-theme-load-path)
           load-file-name)
  ;; Add theme folder to `custom-theme-load-path' when installing over MELPA.
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

;;;######autoload
(when (string-match "/etc/themes/$"
                    (file-name-directory (or load-file-name (buffer-file-name))))
  (message "To stay up-to-date, you should better install and use leuven-theme from MELPA.")
  (sit-for 2))

(provide-theme 'leuven-dark)

;; This is for the sake of Emacs.
;; Local Variables:
;; no-byte-compile: t
;; time-stamp-end: "$"
;; time-stamp-format: "%:y%02m%02d.%02H%02M"
;; time-stamp-start: "Version: "
;; End:

;;; leuven-dark-theme.el ends here
